
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser.js'
export { Prisma }
export * as $Enums from './enums.js'
export * from './enums.js';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Role
 * 
 */
export type Role = Prisma.RoleModel
/**
 * Model PersonnelFile
 * 
 */
export type PersonnelFile = Prisma.PersonnelFileModel
/**
 * Model Site
 * 
 */
export type Site = Prisma.SiteModel
/**
 * Model Shift
 * 
 */
export type Shift = Prisma.ShiftModel
/**
 * Model AssignedShift
 * 
 */
export type AssignedShift = Prisma.AssignedShiftModel
/**
 * Model PatrolRoute
 * 
 */
export type PatrolRoute = Prisma.PatrolRouteModel
/**
 * Model PatrolPoint
 * 
 */
export type PatrolPoint = Prisma.PatrolPointModel
/**
 * Model PatrolLog
 * 
 */
export type PatrolLog = Prisma.PatrolLogModel
/**
 * Model Form
 * 
 */
export type Form = Prisma.FormModel
/**
 * Model FormField
 * 
 */
export type FormField = Prisma.FormFieldModel
/**
 * Model FormResponse
 * 
 */
export type FormResponse = Prisma.FormResponseModel
/**
 * Model FormResponseValue
 * 
 */
export type FormResponseValue = Prisma.FormResponseValueModel
/**
 * Model FormAttachment
 * 
 */
export type FormAttachment = Prisma.FormAttachmentModel
/**
 * Model AuditLog
 * 
 */
export type AuditLog = Prisma.AuditLogModel
