
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 *
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums.js"
import * as $Class from "./internal/class.js"
import * as Prisma from "./internal/prismaNamespace.js"

export * as $Enums from './enums.js'
export * from "./enums.js"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Users
 * const users = await prisma.user.findMany()
 * ```
 * 
 * Read more in our [docs](https://pris.ly/d/client).
 */
export const PrismaClient = $Class.getPrismaClientClass()
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }

/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Role
 * 
 */
export type Role = Prisma.RoleModel
/**
 * Model PersonnelFile
 * 
 */
export type PersonnelFile = Prisma.PersonnelFileModel
/**
 * Model Site
 * 
 */
export type Site = Prisma.SiteModel
/**
 * Model Shift
 * 
 */
export type Shift = Prisma.ShiftModel
/**
 * Model AssignedShift
 * 
 */
export type AssignedShift = Prisma.AssignedShiftModel
/**
 * Model PatrolRoute
 * 
 */
export type PatrolRoute = Prisma.PatrolRouteModel
/**
 * Model PatrolPoint
 * 
 */
export type PatrolPoint = Prisma.PatrolPointModel
/**
 * Model PatrolLog
 * 
 */
export type PatrolLog = Prisma.PatrolLogModel
/**
 * Model Form
 * 
 */
export type Form = Prisma.FormModel
/**
 * Model FormField
 * 
 */
export type FormField = Prisma.FormFieldModel
/**
 * Model FormResponse
 * 
 */
export type FormResponse = Prisma.FormResponseModel
/**
 * Model FormResponseValue
 * 
 */
export type FormResponseValue = Prisma.FormResponseValueModel
/**
 * Model FormAttachment
 * 
 */
export type FormAttachment = Prisma.FormAttachmentModel
/**
 * Model AuditLog
 * 
 */
export type AuditLog = Prisma.AuditLogModel
