import { Permission, PERMISSIONS } from './permissions.constants';

export const roles = ['ADMIN', 'SUPERVISOR', 'GUARD'] as const;
export type RoleName = (typeof roles)[number];
export type RolePermissions = Permission[] | ['*'];

export const ROLE_PERMISSIONS = {
  GUARD: [
    PERMISSIONS.INCIDENT.CREATE,
    PERMISSIONS.INCIDENT.UPDATE_OWN,
    PERMISSIONS.INCIDENT.VIEW_OWN,

    PERMISSIONS.SHIFT.VIEW_OWN,
    PERMISSIONS.SHIFT.CHECKIN,
    PERMISSIONS.SHIFT.CHECKOUT,

    PERMISSIONS.PATROL.EXECUTE,

    PERMISSIONS.REPORT.SUBMIT,
    PERMISSIONS.REPORT.VIEW_OWN,
  ],

  SUPERVISOR: [
    PERMISSIONS.INCIDENT.CREATE,
    PERMISSIONS.INCIDENT.UPDATE_ANY,
    PERMISSIONS.INCIDENT.VIEW_SITE,
    PERMISSIONS.INCIDENT.APPROVE,
    PERMISSIONS.INCIDENT.CLOSE,

    PERMISSIONS.SHIFT.VIEW_TEAM,
    PERMISSIONS.SHIFT.ASSIGN,

    PERMISSIONS.PATROL.VIEW_TEAM,
    PERMISSIONS.PATROL.OVERRIDE,

    PERMISSIONS.REPORT.VIEW_TEAM,
    PERMISSIONS.REPORT.APPROVE,

    PERMISSIONS.USER.VIEW,
  ],

  ADMIN: ['*' as const],
} as const;
