
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AssignedShift` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model AssignedShift
 * 
 */
export type AssignedShiftModel = runtime.Types.Result.DefaultSelection<Prisma.$AssignedShiftPayload>

export type AggregateAssignedShift = {
  _count: AssignedShiftCountAggregateOutputType | null
  _min: AssignedShiftMinAggregateOutputType | null
  _max: AssignedShiftMaxAggregateOutputType | null
}

export type AssignedShiftMinAggregateOutputType = {
  id: string | null
  date: Date | null
  shiftId: string | null
  userId: string | null
  siteId: string | null
}

export type AssignedShiftMaxAggregateOutputType = {
  id: string | null
  date: Date | null
  shiftId: string | null
  userId: string | null
  siteId: string | null
}

export type AssignedShiftCountAggregateOutputType = {
  id: number
  date: number
  shiftId: number
  userId: number
  siteId: number
  _all: number
}


export type AssignedShiftMinAggregateInputType = {
  id?: true
  date?: true
  shiftId?: true
  userId?: true
  siteId?: true
}

export type AssignedShiftMaxAggregateInputType = {
  id?: true
  date?: true
  shiftId?: true
  userId?: true
  siteId?: true
}

export type AssignedShiftCountAggregateInputType = {
  id?: true
  date?: true
  shiftId?: true
  userId?: true
  siteId?: true
  _all?: true
}

export type AssignedShiftAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AssignedShift to aggregate.
   */
  where?: Prisma.AssignedShiftWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssignedShifts to fetch.
   */
  orderBy?: Prisma.AssignedShiftOrderByWithRelationInput | Prisma.AssignedShiftOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AssignedShiftWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssignedShifts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssignedShifts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AssignedShifts
  **/
  _count?: true | AssignedShiftCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AssignedShiftMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AssignedShiftMaxAggregateInputType
}

export type GetAssignedShiftAggregateType<T extends AssignedShiftAggregateArgs> = {
      [P in keyof T & keyof AggregateAssignedShift]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAssignedShift[P]>
    : Prisma.GetScalarType<T[P], AggregateAssignedShift[P]>
}




export type AssignedShiftGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AssignedShiftWhereInput
  orderBy?: Prisma.AssignedShiftOrderByWithAggregationInput | Prisma.AssignedShiftOrderByWithAggregationInput[]
  by: Prisma.AssignedShiftScalarFieldEnum[] | Prisma.AssignedShiftScalarFieldEnum
  having?: Prisma.AssignedShiftScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AssignedShiftCountAggregateInputType | true
  _min?: AssignedShiftMinAggregateInputType
  _max?: AssignedShiftMaxAggregateInputType
}

export type AssignedShiftGroupByOutputType = {
  id: string
  date: Date
  shiftId: string
  userId: string
  siteId: string
  _count: AssignedShiftCountAggregateOutputType | null
  _min: AssignedShiftMinAggregateOutputType | null
  _max: AssignedShiftMaxAggregateOutputType | null
}

type GetAssignedShiftGroupByPayload<T extends AssignedShiftGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AssignedShiftGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AssignedShiftGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AssignedShiftGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AssignedShiftGroupByOutputType[P]>
      }
    >
  >



export type AssignedShiftWhereInput = {
  AND?: Prisma.AssignedShiftWhereInput | Prisma.AssignedShiftWhereInput[]
  OR?: Prisma.AssignedShiftWhereInput[]
  NOT?: Prisma.AssignedShiftWhereInput | Prisma.AssignedShiftWhereInput[]
  id?: Prisma.StringFilter<"AssignedShift"> | string
  date?: Prisma.DateTimeFilter<"AssignedShift"> | Date | string
  shiftId?: Prisma.StringFilter<"AssignedShift"> | string
  userId?: Prisma.StringFilter<"AssignedShift"> | string
  siteId?: Prisma.StringFilter<"AssignedShift"> | string
  shift?: Prisma.XOR<Prisma.ShiftScalarRelationFilter, Prisma.ShiftWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  site?: Prisma.XOR<Prisma.SiteScalarRelationFilter, Prisma.SiteWhereInput>
}

export type AssignedShiftOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  shiftId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  siteId?: Prisma.SortOrder
  shift?: Prisma.ShiftOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
  site?: Prisma.SiteOrderByWithRelationInput
}

export type AssignedShiftWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AssignedShiftWhereInput | Prisma.AssignedShiftWhereInput[]
  OR?: Prisma.AssignedShiftWhereInput[]
  NOT?: Prisma.AssignedShiftWhereInput | Prisma.AssignedShiftWhereInput[]
  date?: Prisma.DateTimeFilter<"AssignedShift"> | Date | string
  shiftId?: Prisma.StringFilter<"AssignedShift"> | string
  userId?: Prisma.StringFilter<"AssignedShift"> | string
  siteId?: Prisma.StringFilter<"AssignedShift"> | string
  shift?: Prisma.XOR<Prisma.ShiftScalarRelationFilter, Prisma.ShiftWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  site?: Prisma.XOR<Prisma.SiteScalarRelationFilter, Prisma.SiteWhereInput>
}, "id">

export type AssignedShiftOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  shiftId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  siteId?: Prisma.SortOrder
  _count?: Prisma.AssignedShiftCountOrderByAggregateInput
  _max?: Prisma.AssignedShiftMaxOrderByAggregateInput
  _min?: Prisma.AssignedShiftMinOrderByAggregateInput
}

export type AssignedShiftScalarWhereWithAggregatesInput = {
  AND?: Prisma.AssignedShiftScalarWhereWithAggregatesInput | Prisma.AssignedShiftScalarWhereWithAggregatesInput[]
  OR?: Prisma.AssignedShiftScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AssignedShiftScalarWhereWithAggregatesInput | Prisma.AssignedShiftScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AssignedShift"> | string
  date?: Prisma.DateTimeWithAggregatesFilter<"AssignedShift"> | Date | string
  shiftId?: Prisma.StringWithAggregatesFilter<"AssignedShift"> | string
  userId?: Prisma.StringWithAggregatesFilter<"AssignedShift"> | string
  siteId?: Prisma.StringWithAggregatesFilter<"AssignedShift"> | string
}

export type AssignedShiftCreateInput = {
  id?: string
  date: Date | string
  shift: Prisma.ShiftCreateNestedOneWithoutAssignedShiftsInput
  user: Prisma.UserCreateNestedOneWithoutAssignedShiftsInput
  site: Prisma.SiteCreateNestedOneWithoutAssignedShiftsInput
}

export type AssignedShiftUncheckedCreateInput = {
  id?: string
  date: Date | string
  shiftId: string
  userId: string
  siteId: string
}

export type AssignedShiftUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shift?: Prisma.ShiftUpdateOneRequiredWithoutAssignedShiftsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutAssignedShiftsNestedInput
  site?: Prisma.SiteUpdateOneRequiredWithoutAssignedShiftsNestedInput
}

export type AssignedShiftUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shiftId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  siteId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AssignedShiftCreateManyInput = {
  id?: string
  date: Date | string
  shiftId: string
  userId: string
  siteId: string
}

export type AssignedShiftUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AssignedShiftUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shiftId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  siteId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AssignedShiftListRelationFilter = {
  every?: Prisma.AssignedShiftWhereInput
  some?: Prisma.AssignedShiftWhereInput
  none?: Prisma.AssignedShiftWhereInput
}

export type AssignedShiftOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AssignedShiftCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  shiftId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  siteId?: Prisma.SortOrder
}

export type AssignedShiftMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  shiftId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  siteId?: Prisma.SortOrder
}

export type AssignedShiftMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  date?: Prisma.SortOrder
  shiftId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  siteId?: Prisma.SortOrder
}

export type AssignedShiftCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AssignedShiftCreateWithoutUserInput, Prisma.AssignedShiftUncheckedCreateWithoutUserInput> | Prisma.AssignedShiftCreateWithoutUserInput[] | Prisma.AssignedShiftUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AssignedShiftCreateOrConnectWithoutUserInput | Prisma.AssignedShiftCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AssignedShiftCreateManyUserInputEnvelope
  connect?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
}

export type AssignedShiftUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AssignedShiftCreateWithoutUserInput, Prisma.AssignedShiftUncheckedCreateWithoutUserInput> | Prisma.AssignedShiftCreateWithoutUserInput[] | Prisma.AssignedShiftUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AssignedShiftCreateOrConnectWithoutUserInput | Prisma.AssignedShiftCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AssignedShiftCreateManyUserInputEnvelope
  connect?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
}

export type AssignedShiftUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AssignedShiftCreateWithoutUserInput, Prisma.AssignedShiftUncheckedCreateWithoutUserInput> | Prisma.AssignedShiftCreateWithoutUserInput[] | Prisma.AssignedShiftUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AssignedShiftCreateOrConnectWithoutUserInput | Prisma.AssignedShiftCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AssignedShiftUpsertWithWhereUniqueWithoutUserInput | Prisma.AssignedShiftUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AssignedShiftCreateManyUserInputEnvelope
  set?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  disconnect?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  delete?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  connect?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  update?: Prisma.AssignedShiftUpdateWithWhereUniqueWithoutUserInput | Prisma.AssignedShiftUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AssignedShiftUpdateManyWithWhereWithoutUserInput | Prisma.AssignedShiftUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AssignedShiftScalarWhereInput | Prisma.AssignedShiftScalarWhereInput[]
}

export type AssignedShiftUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AssignedShiftCreateWithoutUserInput, Prisma.AssignedShiftUncheckedCreateWithoutUserInput> | Prisma.AssignedShiftCreateWithoutUserInput[] | Prisma.AssignedShiftUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AssignedShiftCreateOrConnectWithoutUserInput | Prisma.AssignedShiftCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AssignedShiftUpsertWithWhereUniqueWithoutUserInput | Prisma.AssignedShiftUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AssignedShiftCreateManyUserInputEnvelope
  set?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  disconnect?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  delete?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  connect?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  update?: Prisma.AssignedShiftUpdateWithWhereUniqueWithoutUserInput | Prisma.AssignedShiftUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AssignedShiftUpdateManyWithWhereWithoutUserInput | Prisma.AssignedShiftUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AssignedShiftScalarWhereInput | Prisma.AssignedShiftScalarWhereInput[]
}

export type AssignedShiftCreateNestedManyWithoutSiteInput = {
  create?: Prisma.XOR<Prisma.AssignedShiftCreateWithoutSiteInput, Prisma.AssignedShiftUncheckedCreateWithoutSiteInput> | Prisma.AssignedShiftCreateWithoutSiteInput[] | Prisma.AssignedShiftUncheckedCreateWithoutSiteInput[]
  connectOrCreate?: Prisma.AssignedShiftCreateOrConnectWithoutSiteInput | Prisma.AssignedShiftCreateOrConnectWithoutSiteInput[]
  createMany?: Prisma.AssignedShiftCreateManySiteInputEnvelope
  connect?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
}

export type AssignedShiftUncheckedCreateNestedManyWithoutSiteInput = {
  create?: Prisma.XOR<Prisma.AssignedShiftCreateWithoutSiteInput, Prisma.AssignedShiftUncheckedCreateWithoutSiteInput> | Prisma.AssignedShiftCreateWithoutSiteInput[] | Prisma.AssignedShiftUncheckedCreateWithoutSiteInput[]
  connectOrCreate?: Prisma.AssignedShiftCreateOrConnectWithoutSiteInput | Prisma.AssignedShiftCreateOrConnectWithoutSiteInput[]
  createMany?: Prisma.AssignedShiftCreateManySiteInputEnvelope
  connect?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
}

export type AssignedShiftUpdateManyWithoutSiteNestedInput = {
  create?: Prisma.XOR<Prisma.AssignedShiftCreateWithoutSiteInput, Prisma.AssignedShiftUncheckedCreateWithoutSiteInput> | Prisma.AssignedShiftCreateWithoutSiteInput[] | Prisma.AssignedShiftUncheckedCreateWithoutSiteInput[]
  connectOrCreate?: Prisma.AssignedShiftCreateOrConnectWithoutSiteInput | Prisma.AssignedShiftCreateOrConnectWithoutSiteInput[]
  upsert?: Prisma.AssignedShiftUpsertWithWhereUniqueWithoutSiteInput | Prisma.AssignedShiftUpsertWithWhereUniqueWithoutSiteInput[]
  createMany?: Prisma.AssignedShiftCreateManySiteInputEnvelope
  set?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  disconnect?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  delete?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  connect?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  update?: Prisma.AssignedShiftUpdateWithWhereUniqueWithoutSiteInput | Prisma.AssignedShiftUpdateWithWhereUniqueWithoutSiteInput[]
  updateMany?: Prisma.AssignedShiftUpdateManyWithWhereWithoutSiteInput | Prisma.AssignedShiftUpdateManyWithWhereWithoutSiteInput[]
  deleteMany?: Prisma.AssignedShiftScalarWhereInput | Prisma.AssignedShiftScalarWhereInput[]
}

export type AssignedShiftUncheckedUpdateManyWithoutSiteNestedInput = {
  create?: Prisma.XOR<Prisma.AssignedShiftCreateWithoutSiteInput, Prisma.AssignedShiftUncheckedCreateWithoutSiteInput> | Prisma.AssignedShiftCreateWithoutSiteInput[] | Prisma.AssignedShiftUncheckedCreateWithoutSiteInput[]
  connectOrCreate?: Prisma.AssignedShiftCreateOrConnectWithoutSiteInput | Prisma.AssignedShiftCreateOrConnectWithoutSiteInput[]
  upsert?: Prisma.AssignedShiftUpsertWithWhereUniqueWithoutSiteInput | Prisma.AssignedShiftUpsertWithWhereUniqueWithoutSiteInput[]
  createMany?: Prisma.AssignedShiftCreateManySiteInputEnvelope
  set?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  disconnect?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  delete?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  connect?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  update?: Prisma.AssignedShiftUpdateWithWhereUniqueWithoutSiteInput | Prisma.AssignedShiftUpdateWithWhereUniqueWithoutSiteInput[]
  updateMany?: Prisma.AssignedShiftUpdateManyWithWhereWithoutSiteInput | Prisma.AssignedShiftUpdateManyWithWhereWithoutSiteInput[]
  deleteMany?: Prisma.AssignedShiftScalarWhereInput | Prisma.AssignedShiftScalarWhereInput[]
}

export type AssignedShiftCreateNestedManyWithoutShiftInput = {
  create?: Prisma.XOR<Prisma.AssignedShiftCreateWithoutShiftInput, Prisma.AssignedShiftUncheckedCreateWithoutShiftInput> | Prisma.AssignedShiftCreateWithoutShiftInput[] | Prisma.AssignedShiftUncheckedCreateWithoutShiftInput[]
  connectOrCreate?: Prisma.AssignedShiftCreateOrConnectWithoutShiftInput | Prisma.AssignedShiftCreateOrConnectWithoutShiftInput[]
  createMany?: Prisma.AssignedShiftCreateManyShiftInputEnvelope
  connect?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
}

export type AssignedShiftUncheckedCreateNestedManyWithoutShiftInput = {
  create?: Prisma.XOR<Prisma.AssignedShiftCreateWithoutShiftInput, Prisma.AssignedShiftUncheckedCreateWithoutShiftInput> | Prisma.AssignedShiftCreateWithoutShiftInput[] | Prisma.AssignedShiftUncheckedCreateWithoutShiftInput[]
  connectOrCreate?: Prisma.AssignedShiftCreateOrConnectWithoutShiftInput | Prisma.AssignedShiftCreateOrConnectWithoutShiftInput[]
  createMany?: Prisma.AssignedShiftCreateManyShiftInputEnvelope
  connect?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
}

export type AssignedShiftUpdateManyWithoutShiftNestedInput = {
  create?: Prisma.XOR<Prisma.AssignedShiftCreateWithoutShiftInput, Prisma.AssignedShiftUncheckedCreateWithoutShiftInput> | Prisma.AssignedShiftCreateWithoutShiftInput[] | Prisma.AssignedShiftUncheckedCreateWithoutShiftInput[]
  connectOrCreate?: Prisma.AssignedShiftCreateOrConnectWithoutShiftInput | Prisma.AssignedShiftCreateOrConnectWithoutShiftInput[]
  upsert?: Prisma.AssignedShiftUpsertWithWhereUniqueWithoutShiftInput | Prisma.AssignedShiftUpsertWithWhereUniqueWithoutShiftInput[]
  createMany?: Prisma.AssignedShiftCreateManyShiftInputEnvelope
  set?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  disconnect?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  delete?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  connect?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  update?: Prisma.AssignedShiftUpdateWithWhereUniqueWithoutShiftInput | Prisma.AssignedShiftUpdateWithWhereUniqueWithoutShiftInput[]
  updateMany?: Prisma.AssignedShiftUpdateManyWithWhereWithoutShiftInput | Prisma.AssignedShiftUpdateManyWithWhereWithoutShiftInput[]
  deleteMany?: Prisma.AssignedShiftScalarWhereInput | Prisma.AssignedShiftScalarWhereInput[]
}

export type AssignedShiftUncheckedUpdateManyWithoutShiftNestedInput = {
  create?: Prisma.XOR<Prisma.AssignedShiftCreateWithoutShiftInput, Prisma.AssignedShiftUncheckedCreateWithoutShiftInput> | Prisma.AssignedShiftCreateWithoutShiftInput[] | Prisma.AssignedShiftUncheckedCreateWithoutShiftInput[]
  connectOrCreate?: Prisma.AssignedShiftCreateOrConnectWithoutShiftInput | Prisma.AssignedShiftCreateOrConnectWithoutShiftInput[]
  upsert?: Prisma.AssignedShiftUpsertWithWhereUniqueWithoutShiftInput | Prisma.AssignedShiftUpsertWithWhereUniqueWithoutShiftInput[]
  createMany?: Prisma.AssignedShiftCreateManyShiftInputEnvelope
  set?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  disconnect?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  delete?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  connect?: Prisma.AssignedShiftWhereUniqueInput | Prisma.AssignedShiftWhereUniqueInput[]
  update?: Prisma.AssignedShiftUpdateWithWhereUniqueWithoutShiftInput | Prisma.AssignedShiftUpdateWithWhereUniqueWithoutShiftInput[]
  updateMany?: Prisma.AssignedShiftUpdateManyWithWhereWithoutShiftInput | Prisma.AssignedShiftUpdateManyWithWhereWithoutShiftInput[]
  deleteMany?: Prisma.AssignedShiftScalarWhereInput | Prisma.AssignedShiftScalarWhereInput[]
}

export type AssignedShiftCreateWithoutUserInput = {
  id?: string
  date: Date | string
  shift: Prisma.ShiftCreateNestedOneWithoutAssignedShiftsInput
  site: Prisma.SiteCreateNestedOneWithoutAssignedShiftsInput
}

export type AssignedShiftUncheckedCreateWithoutUserInput = {
  id?: string
  date: Date | string
  shiftId: string
  siteId: string
}

export type AssignedShiftCreateOrConnectWithoutUserInput = {
  where: Prisma.AssignedShiftWhereUniqueInput
  create: Prisma.XOR<Prisma.AssignedShiftCreateWithoutUserInput, Prisma.AssignedShiftUncheckedCreateWithoutUserInput>
}

export type AssignedShiftCreateManyUserInputEnvelope = {
  data: Prisma.AssignedShiftCreateManyUserInput | Prisma.AssignedShiftCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type AssignedShiftUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.AssignedShiftWhereUniqueInput
  update: Prisma.XOR<Prisma.AssignedShiftUpdateWithoutUserInput, Prisma.AssignedShiftUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.AssignedShiftCreateWithoutUserInput, Prisma.AssignedShiftUncheckedCreateWithoutUserInput>
}

export type AssignedShiftUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.AssignedShiftWhereUniqueInput
  data: Prisma.XOR<Prisma.AssignedShiftUpdateWithoutUserInput, Prisma.AssignedShiftUncheckedUpdateWithoutUserInput>
}

export type AssignedShiftUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.AssignedShiftScalarWhereInput
  data: Prisma.XOR<Prisma.AssignedShiftUpdateManyMutationInput, Prisma.AssignedShiftUncheckedUpdateManyWithoutUserInput>
}

export type AssignedShiftScalarWhereInput = {
  AND?: Prisma.AssignedShiftScalarWhereInput | Prisma.AssignedShiftScalarWhereInput[]
  OR?: Prisma.AssignedShiftScalarWhereInput[]
  NOT?: Prisma.AssignedShiftScalarWhereInput | Prisma.AssignedShiftScalarWhereInput[]
  id?: Prisma.StringFilter<"AssignedShift"> | string
  date?: Prisma.DateTimeFilter<"AssignedShift"> | Date | string
  shiftId?: Prisma.StringFilter<"AssignedShift"> | string
  userId?: Prisma.StringFilter<"AssignedShift"> | string
  siteId?: Prisma.StringFilter<"AssignedShift"> | string
}

export type AssignedShiftCreateWithoutSiteInput = {
  id?: string
  date: Date | string
  shift: Prisma.ShiftCreateNestedOneWithoutAssignedShiftsInput
  user: Prisma.UserCreateNestedOneWithoutAssignedShiftsInput
}

export type AssignedShiftUncheckedCreateWithoutSiteInput = {
  id?: string
  date: Date | string
  shiftId: string
  userId: string
}

export type AssignedShiftCreateOrConnectWithoutSiteInput = {
  where: Prisma.AssignedShiftWhereUniqueInput
  create: Prisma.XOR<Prisma.AssignedShiftCreateWithoutSiteInput, Prisma.AssignedShiftUncheckedCreateWithoutSiteInput>
}

export type AssignedShiftCreateManySiteInputEnvelope = {
  data: Prisma.AssignedShiftCreateManySiteInput | Prisma.AssignedShiftCreateManySiteInput[]
  skipDuplicates?: boolean
}

export type AssignedShiftUpsertWithWhereUniqueWithoutSiteInput = {
  where: Prisma.AssignedShiftWhereUniqueInput
  update: Prisma.XOR<Prisma.AssignedShiftUpdateWithoutSiteInput, Prisma.AssignedShiftUncheckedUpdateWithoutSiteInput>
  create: Prisma.XOR<Prisma.AssignedShiftCreateWithoutSiteInput, Prisma.AssignedShiftUncheckedCreateWithoutSiteInput>
}

export type AssignedShiftUpdateWithWhereUniqueWithoutSiteInput = {
  where: Prisma.AssignedShiftWhereUniqueInput
  data: Prisma.XOR<Prisma.AssignedShiftUpdateWithoutSiteInput, Prisma.AssignedShiftUncheckedUpdateWithoutSiteInput>
}

export type AssignedShiftUpdateManyWithWhereWithoutSiteInput = {
  where: Prisma.AssignedShiftScalarWhereInput
  data: Prisma.XOR<Prisma.AssignedShiftUpdateManyMutationInput, Prisma.AssignedShiftUncheckedUpdateManyWithoutSiteInput>
}

export type AssignedShiftCreateWithoutShiftInput = {
  id?: string
  date: Date | string
  user: Prisma.UserCreateNestedOneWithoutAssignedShiftsInput
  site: Prisma.SiteCreateNestedOneWithoutAssignedShiftsInput
}

export type AssignedShiftUncheckedCreateWithoutShiftInput = {
  id?: string
  date: Date | string
  userId: string
  siteId: string
}

export type AssignedShiftCreateOrConnectWithoutShiftInput = {
  where: Prisma.AssignedShiftWhereUniqueInput
  create: Prisma.XOR<Prisma.AssignedShiftCreateWithoutShiftInput, Prisma.AssignedShiftUncheckedCreateWithoutShiftInput>
}

export type AssignedShiftCreateManyShiftInputEnvelope = {
  data: Prisma.AssignedShiftCreateManyShiftInput | Prisma.AssignedShiftCreateManyShiftInput[]
  skipDuplicates?: boolean
}

export type AssignedShiftUpsertWithWhereUniqueWithoutShiftInput = {
  where: Prisma.AssignedShiftWhereUniqueInput
  update: Prisma.XOR<Prisma.AssignedShiftUpdateWithoutShiftInput, Prisma.AssignedShiftUncheckedUpdateWithoutShiftInput>
  create: Prisma.XOR<Prisma.AssignedShiftCreateWithoutShiftInput, Prisma.AssignedShiftUncheckedCreateWithoutShiftInput>
}

export type AssignedShiftUpdateWithWhereUniqueWithoutShiftInput = {
  where: Prisma.AssignedShiftWhereUniqueInput
  data: Prisma.XOR<Prisma.AssignedShiftUpdateWithoutShiftInput, Prisma.AssignedShiftUncheckedUpdateWithoutShiftInput>
}

export type AssignedShiftUpdateManyWithWhereWithoutShiftInput = {
  where: Prisma.AssignedShiftScalarWhereInput
  data: Prisma.XOR<Prisma.AssignedShiftUpdateManyMutationInput, Prisma.AssignedShiftUncheckedUpdateManyWithoutShiftInput>
}

export type AssignedShiftCreateManyUserInput = {
  id?: string
  date: Date | string
  shiftId: string
  siteId: string
}

export type AssignedShiftUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shift?: Prisma.ShiftUpdateOneRequiredWithoutAssignedShiftsNestedInput
  site?: Prisma.SiteUpdateOneRequiredWithoutAssignedShiftsNestedInput
}

export type AssignedShiftUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shiftId?: Prisma.StringFieldUpdateOperationsInput | string
  siteId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AssignedShiftUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shiftId?: Prisma.StringFieldUpdateOperationsInput | string
  siteId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AssignedShiftCreateManySiteInput = {
  id?: string
  date: Date | string
  shiftId: string
  userId: string
}

export type AssignedShiftUpdateWithoutSiteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shift?: Prisma.ShiftUpdateOneRequiredWithoutAssignedShiftsNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutAssignedShiftsNestedInput
}

export type AssignedShiftUncheckedUpdateWithoutSiteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shiftId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AssignedShiftUncheckedUpdateManyWithoutSiteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  shiftId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AssignedShiftCreateManyShiftInput = {
  id?: string
  date: Date | string
  userId: string
  siteId: string
}

export type AssignedShiftUpdateWithoutShiftInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutAssignedShiftsNestedInput
  site?: Prisma.SiteUpdateOneRequiredWithoutAssignedShiftsNestedInput
}

export type AssignedShiftUncheckedUpdateWithoutShiftInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  siteId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type AssignedShiftUncheckedUpdateManyWithoutShiftInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  siteId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type AssignedShiftSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  shiftId?: boolean
  userId?: boolean
  siteId?: boolean
  shift?: boolean | Prisma.ShiftDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  site?: boolean | Prisma.SiteDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assignedShift"]>

export type AssignedShiftSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  shiftId?: boolean
  userId?: boolean
  siteId?: boolean
  shift?: boolean | Prisma.ShiftDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  site?: boolean | Prisma.SiteDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assignedShift"]>

export type AssignedShiftSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  date?: boolean
  shiftId?: boolean
  userId?: boolean
  siteId?: boolean
  shift?: boolean | Prisma.ShiftDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  site?: boolean | Prisma.SiteDefaultArgs<ExtArgs>
}, ExtArgs["result"]["assignedShift"]>

export type AssignedShiftSelectScalar = {
  id?: boolean
  date?: boolean
  shiftId?: boolean
  userId?: boolean
  siteId?: boolean
}

export type AssignedShiftOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "date" | "shiftId" | "userId" | "siteId", ExtArgs["result"]["assignedShift"]>
export type AssignedShiftInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  shift?: boolean | Prisma.ShiftDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  site?: boolean | Prisma.SiteDefaultArgs<ExtArgs>
}
export type AssignedShiftIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  shift?: boolean | Prisma.ShiftDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  site?: boolean | Prisma.SiteDefaultArgs<ExtArgs>
}
export type AssignedShiftIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  shift?: boolean | Prisma.ShiftDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  site?: boolean | Prisma.SiteDefaultArgs<ExtArgs>
}

export type $AssignedShiftPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AssignedShift"
  objects: {
    shift: Prisma.$ShiftPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
    site: Prisma.$SitePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    date: Date
    shiftId: string
    userId: string
    siteId: string
  }, ExtArgs["result"]["assignedShift"]>
  composites: {}
}

export type AssignedShiftGetPayload<S extends boolean | null | undefined | AssignedShiftDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AssignedShiftPayload, S>

export type AssignedShiftCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AssignedShiftFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AssignedShiftCountAggregateInputType | true
  }

export interface AssignedShiftDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AssignedShift'], meta: { name: 'AssignedShift' } }
  /**
   * Find zero or one AssignedShift that matches the filter.
   * @param {AssignedShiftFindUniqueArgs} args - Arguments to find a AssignedShift
   * @example
   * // Get one AssignedShift
   * const assignedShift = await prisma.assignedShift.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AssignedShiftFindUniqueArgs>(args: Prisma.SelectSubset<T, AssignedShiftFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AssignedShiftClient<runtime.Types.Result.GetResult<Prisma.$AssignedShiftPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AssignedShift that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AssignedShiftFindUniqueOrThrowArgs} args - Arguments to find a AssignedShift
   * @example
   * // Get one AssignedShift
   * const assignedShift = await prisma.assignedShift.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AssignedShiftFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AssignedShiftFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssignedShiftClient<runtime.Types.Result.GetResult<Prisma.$AssignedShiftPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AssignedShift that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssignedShiftFindFirstArgs} args - Arguments to find a AssignedShift
   * @example
   * // Get one AssignedShift
   * const assignedShift = await prisma.assignedShift.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AssignedShiftFindFirstArgs>(args?: Prisma.SelectSubset<T, AssignedShiftFindFirstArgs<ExtArgs>>): Prisma.Prisma__AssignedShiftClient<runtime.Types.Result.GetResult<Prisma.$AssignedShiftPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AssignedShift that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssignedShiftFindFirstOrThrowArgs} args - Arguments to find a AssignedShift
   * @example
   * // Get one AssignedShift
   * const assignedShift = await prisma.assignedShift.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AssignedShiftFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AssignedShiftFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AssignedShiftClient<runtime.Types.Result.GetResult<Prisma.$AssignedShiftPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AssignedShifts that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssignedShiftFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AssignedShifts
   * const assignedShifts = await prisma.assignedShift.findMany()
   * 
   * // Get first 10 AssignedShifts
   * const assignedShifts = await prisma.assignedShift.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const assignedShiftWithIdOnly = await prisma.assignedShift.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AssignedShiftFindManyArgs>(args?: Prisma.SelectSubset<T, AssignedShiftFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssignedShiftPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AssignedShift.
   * @param {AssignedShiftCreateArgs} args - Arguments to create a AssignedShift.
   * @example
   * // Create one AssignedShift
   * const AssignedShift = await prisma.assignedShift.create({
   *   data: {
   *     // ... data to create a AssignedShift
   *   }
   * })
   * 
   */
  create<T extends AssignedShiftCreateArgs>(args: Prisma.SelectSubset<T, AssignedShiftCreateArgs<ExtArgs>>): Prisma.Prisma__AssignedShiftClient<runtime.Types.Result.GetResult<Prisma.$AssignedShiftPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AssignedShifts.
   * @param {AssignedShiftCreateManyArgs} args - Arguments to create many AssignedShifts.
   * @example
   * // Create many AssignedShifts
   * const assignedShift = await prisma.assignedShift.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AssignedShiftCreateManyArgs>(args?: Prisma.SelectSubset<T, AssignedShiftCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AssignedShifts and returns the data saved in the database.
   * @param {AssignedShiftCreateManyAndReturnArgs} args - Arguments to create many AssignedShifts.
   * @example
   * // Create many AssignedShifts
   * const assignedShift = await prisma.assignedShift.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AssignedShifts and only return the `id`
   * const assignedShiftWithIdOnly = await prisma.assignedShift.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AssignedShiftCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AssignedShiftCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssignedShiftPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AssignedShift.
   * @param {AssignedShiftDeleteArgs} args - Arguments to delete one AssignedShift.
   * @example
   * // Delete one AssignedShift
   * const AssignedShift = await prisma.assignedShift.delete({
   *   where: {
   *     // ... filter to delete one AssignedShift
   *   }
   * })
   * 
   */
  delete<T extends AssignedShiftDeleteArgs>(args: Prisma.SelectSubset<T, AssignedShiftDeleteArgs<ExtArgs>>): Prisma.Prisma__AssignedShiftClient<runtime.Types.Result.GetResult<Prisma.$AssignedShiftPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AssignedShift.
   * @param {AssignedShiftUpdateArgs} args - Arguments to update one AssignedShift.
   * @example
   * // Update one AssignedShift
   * const assignedShift = await prisma.assignedShift.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AssignedShiftUpdateArgs>(args: Prisma.SelectSubset<T, AssignedShiftUpdateArgs<ExtArgs>>): Prisma.Prisma__AssignedShiftClient<runtime.Types.Result.GetResult<Prisma.$AssignedShiftPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AssignedShifts.
   * @param {AssignedShiftDeleteManyArgs} args - Arguments to filter AssignedShifts to delete.
   * @example
   * // Delete a few AssignedShifts
   * const { count } = await prisma.assignedShift.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AssignedShiftDeleteManyArgs>(args?: Prisma.SelectSubset<T, AssignedShiftDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AssignedShifts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssignedShiftUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AssignedShifts
   * const assignedShift = await prisma.assignedShift.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AssignedShiftUpdateManyArgs>(args: Prisma.SelectSubset<T, AssignedShiftUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AssignedShifts and returns the data updated in the database.
   * @param {AssignedShiftUpdateManyAndReturnArgs} args - Arguments to update many AssignedShifts.
   * @example
   * // Update many AssignedShifts
   * const assignedShift = await prisma.assignedShift.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AssignedShifts and only return the `id`
   * const assignedShiftWithIdOnly = await prisma.assignedShift.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AssignedShiftUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AssignedShiftUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AssignedShiftPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AssignedShift.
   * @param {AssignedShiftUpsertArgs} args - Arguments to update or create a AssignedShift.
   * @example
   * // Update or create a AssignedShift
   * const assignedShift = await prisma.assignedShift.upsert({
   *   create: {
   *     // ... data to create a AssignedShift
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AssignedShift we want to update
   *   }
   * })
   */
  upsert<T extends AssignedShiftUpsertArgs>(args: Prisma.SelectSubset<T, AssignedShiftUpsertArgs<ExtArgs>>): Prisma.Prisma__AssignedShiftClient<runtime.Types.Result.GetResult<Prisma.$AssignedShiftPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AssignedShifts.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssignedShiftCountArgs} args - Arguments to filter AssignedShifts to count.
   * @example
   * // Count the number of AssignedShifts
   * const count = await prisma.assignedShift.count({
   *   where: {
   *     // ... the filter for the AssignedShifts we want to count
   *   }
   * })
  **/
  count<T extends AssignedShiftCountArgs>(
    args?: Prisma.Subset<T, AssignedShiftCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AssignedShiftCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AssignedShift.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssignedShiftAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AssignedShiftAggregateArgs>(args: Prisma.Subset<T, AssignedShiftAggregateArgs>): Prisma.PrismaPromise<GetAssignedShiftAggregateType<T>>

  /**
   * Group by AssignedShift.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AssignedShiftGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AssignedShiftGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AssignedShiftGroupByArgs['orderBy'] }
      : { orderBy?: AssignedShiftGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AssignedShiftGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAssignedShiftGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AssignedShift model
 */
readonly fields: AssignedShiftFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AssignedShift.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AssignedShiftClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  shift<T extends Prisma.ShiftDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ShiftDefaultArgs<ExtArgs>>): Prisma.Prisma__ShiftClient<runtime.Types.Result.GetResult<Prisma.$ShiftPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  site<T extends Prisma.SiteDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SiteDefaultArgs<ExtArgs>>): Prisma.Prisma__SiteClient<runtime.Types.Result.GetResult<Prisma.$SitePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AssignedShift model
 */
export interface AssignedShiftFieldRefs {
  readonly id: Prisma.FieldRef<"AssignedShift", 'String'>
  readonly date: Prisma.FieldRef<"AssignedShift", 'DateTime'>
  readonly shiftId: Prisma.FieldRef<"AssignedShift", 'String'>
  readonly userId: Prisma.FieldRef<"AssignedShift", 'String'>
  readonly siteId: Prisma.FieldRef<"AssignedShift", 'String'>
}
    

// Custom InputTypes
/**
 * AssignedShift findUnique
 */
export type AssignedShiftFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssignedShift
   */
  select?: Prisma.AssignedShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssignedShift
   */
  omit?: Prisma.AssignedShiftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssignedShiftInclude<ExtArgs> | null
  /**
   * Filter, which AssignedShift to fetch.
   */
  where: Prisma.AssignedShiftWhereUniqueInput
}

/**
 * AssignedShift findUniqueOrThrow
 */
export type AssignedShiftFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssignedShift
   */
  select?: Prisma.AssignedShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssignedShift
   */
  omit?: Prisma.AssignedShiftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssignedShiftInclude<ExtArgs> | null
  /**
   * Filter, which AssignedShift to fetch.
   */
  where: Prisma.AssignedShiftWhereUniqueInput
}

/**
 * AssignedShift findFirst
 */
export type AssignedShiftFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssignedShift
   */
  select?: Prisma.AssignedShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssignedShift
   */
  omit?: Prisma.AssignedShiftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssignedShiftInclude<ExtArgs> | null
  /**
   * Filter, which AssignedShift to fetch.
   */
  where?: Prisma.AssignedShiftWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssignedShifts to fetch.
   */
  orderBy?: Prisma.AssignedShiftOrderByWithRelationInput | Prisma.AssignedShiftOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AssignedShifts.
   */
  cursor?: Prisma.AssignedShiftWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssignedShifts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssignedShifts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AssignedShifts.
   */
  distinct?: Prisma.AssignedShiftScalarFieldEnum | Prisma.AssignedShiftScalarFieldEnum[]
}

/**
 * AssignedShift findFirstOrThrow
 */
export type AssignedShiftFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssignedShift
   */
  select?: Prisma.AssignedShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssignedShift
   */
  omit?: Prisma.AssignedShiftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssignedShiftInclude<ExtArgs> | null
  /**
   * Filter, which AssignedShift to fetch.
   */
  where?: Prisma.AssignedShiftWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssignedShifts to fetch.
   */
  orderBy?: Prisma.AssignedShiftOrderByWithRelationInput | Prisma.AssignedShiftOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AssignedShifts.
   */
  cursor?: Prisma.AssignedShiftWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssignedShifts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssignedShifts.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AssignedShifts.
   */
  distinct?: Prisma.AssignedShiftScalarFieldEnum | Prisma.AssignedShiftScalarFieldEnum[]
}

/**
 * AssignedShift findMany
 */
export type AssignedShiftFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssignedShift
   */
  select?: Prisma.AssignedShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssignedShift
   */
  omit?: Prisma.AssignedShiftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssignedShiftInclude<ExtArgs> | null
  /**
   * Filter, which AssignedShifts to fetch.
   */
  where?: Prisma.AssignedShiftWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AssignedShifts to fetch.
   */
  orderBy?: Prisma.AssignedShiftOrderByWithRelationInput | Prisma.AssignedShiftOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AssignedShifts.
   */
  cursor?: Prisma.AssignedShiftWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AssignedShifts from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AssignedShifts.
   */
  skip?: number
  distinct?: Prisma.AssignedShiftScalarFieldEnum | Prisma.AssignedShiftScalarFieldEnum[]
}

/**
 * AssignedShift create
 */
export type AssignedShiftCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssignedShift
   */
  select?: Prisma.AssignedShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssignedShift
   */
  omit?: Prisma.AssignedShiftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssignedShiftInclude<ExtArgs> | null
  /**
   * The data needed to create a AssignedShift.
   */
  data: Prisma.XOR<Prisma.AssignedShiftCreateInput, Prisma.AssignedShiftUncheckedCreateInput>
}

/**
 * AssignedShift createMany
 */
export type AssignedShiftCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AssignedShifts.
   */
  data: Prisma.AssignedShiftCreateManyInput | Prisma.AssignedShiftCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AssignedShift createManyAndReturn
 */
export type AssignedShiftCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssignedShift
   */
  select?: Prisma.AssignedShiftSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AssignedShift
   */
  omit?: Prisma.AssignedShiftOmit<ExtArgs> | null
  /**
   * The data used to create many AssignedShifts.
   */
  data: Prisma.AssignedShiftCreateManyInput | Prisma.AssignedShiftCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssignedShiftIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AssignedShift update
 */
export type AssignedShiftUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssignedShift
   */
  select?: Prisma.AssignedShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssignedShift
   */
  omit?: Prisma.AssignedShiftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssignedShiftInclude<ExtArgs> | null
  /**
   * The data needed to update a AssignedShift.
   */
  data: Prisma.XOR<Prisma.AssignedShiftUpdateInput, Prisma.AssignedShiftUncheckedUpdateInput>
  /**
   * Choose, which AssignedShift to update.
   */
  where: Prisma.AssignedShiftWhereUniqueInput
}

/**
 * AssignedShift updateMany
 */
export type AssignedShiftUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AssignedShifts.
   */
  data: Prisma.XOR<Prisma.AssignedShiftUpdateManyMutationInput, Prisma.AssignedShiftUncheckedUpdateManyInput>
  /**
   * Filter which AssignedShifts to update
   */
  where?: Prisma.AssignedShiftWhereInput
  /**
   * Limit how many AssignedShifts to update.
   */
  limit?: number
}

/**
 * AssignedShift updateManyAndReturn
 */
export type AssignedShiftUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssignedShift
   */
  select?: Prisma.AssignedShiftSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AssignedShift
   */
  omit?: Prisma.AssignedShiftOmit<ExtArgs> | null
  /**
   * The data used to update AssignedShifts.
   */
  data: Prisma.XOR<Prisma.AssignedShiftUpdateManyMutationInput, Prisma.AssignedShiftUncheckedUpdateManyInput>
  /**
   * Filter which AssignedShifts to update
   */
  where?: Prisma.AssignedShiftWhereInput
  /**
   * Limit how many AssignedShifts to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssignedShiftIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AssignedShift upsert
 */
export type AssignedShiftUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssignedShift
   */
  select?: Prisma.AssignedShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssignedShift
   */
  omit?: Prisma.AssignedShiftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssignedShiftInclude<ExtArgs> | null
  /**
   * The filter to search for the AssignedShift to update in case it exists.
   */
  where: Prisma.AssignedShiftWhereUniqueInput
  /**
   * In case the AssignedShift found by the `where` argument doesn't exist, create a new AssignedShift with this data.
   */
  create: Prisma.XOR<Prisma.AssignedShiftCreateInput, Prisma.AssignedShiftUncheckedCreateInput>
  /**
   * In case the AssignedShift was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AssignedShiftUpdateInput, Prisma.AssignedShiftUncheckedUpdateInput>
}

/**
 * AssignedShift delete
 */
export type AssignedShiftDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssignedShift
   */
  select?: Prisma.AssignedShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssignedShift
   */
  omit?: Prisma.AssignedShiftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssignedShiftInclude<ExtArgs> | null
  /**
   * Filter which AssignedShift to delete.
   */
  where: Prisma.AssignedShiftWhereUniqueInput
}

/**
 * AssignedShift deleteMany
 */
export type AssignedShiftDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AssignedShifts to delete
   */
  where?: Prisma.AssignedShiftWhereInput
  /**
   * Limit how many AssignedShifts to delete.
   */
  limit?: number
}

/**
 * AssignedShift without action
 */
export type AssignedShiftDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AssignedShift
   */
  select?: Prisma.AssignedShiftSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AssignedShift
   */
  omit?: Prisma.AssignedShiftOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AssignedShiftInclude<ExtArgs> | null
}
