
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PatrolRoute` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model PatrolRoute
 * 
 */
export type PatrolRouteModel = runtime.Types.Result.DefaultSelection<Prisma.$PatrolRoutePayload>

export type AggregatePatrolRoute = {
  _count: PatrolRouteCountAggregateOutputType | null
  _min: PatrolRouteMinAggregateOutputType | null
  _max: PatrolRouteMaxAggregateOutputType | null
}

export type PatrolRouteMinAggregateOutputType = {
  id: string | null
  siteId: string | null
  name: string | null
}

export type PatrolRouteMaxAggregateOutputType = {
  id: string | null
  siteId: string | null
  name: string | null
}

export type PatrolRouteCountAggregateOutputType = {
  id: number
  siteId: number
  name: number
  _all: number
}


export type PatrolRouteMinAggregateInputType = {
  id?: true
  siteId?: true
  name?: true
}

export type PatrolRouteMaxAggregateInputType = {
  id?: true
  siteId?: true
  name?: true
}

export type PatrolRouteCountAggregateInputType = {
  id?: true
  siteId?: true
  name?: true
  _all?: true
}

export type PatrolRouteAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PatrolRoute to aggregate.
   */
  where?: Prisma.PatrolRouteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PatrolRoutes to fetch.
   */
  orderBy?: Prisma.PatrolRouteOrderByWithRelationInput | Prisma.PatrolRouteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PatrolRouteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PatrolRoutes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PatrolRoutes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PatrolRoutes
  **/
  _count?: true | PatrolRouteCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PatrolRouteMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PatrolRouteMaxAggregateInputType
}

export type GetPatrolRouteAggregateType<T extends PatrolRouteAggregateArgs> = {
      [P in keyof T & keyof AggregatePatrolRoute]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePatrolRoute[P]>
    : Prisma.GetScalarType<T[P], AggregatePatrolRoute[P]>
}




export type PatrolRouteGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PatrolRouteWhereInput
  orderBy?: Prisma.PatrolRouteOrderByWithAggregationInput | Prisma.PatrolRouteOrderByWithAggregationInput[]
  by: Prisma.PatrolRouteScalarFieldEnum[] | Prisma.PatrolRouteScalarFieldEnum
  having?: Prisma.PatrolRouteScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PatrolRouteCountAggregateInputType | true
  _min?: PatrolRouteMinAggregateInputType
  _max?: PatrolRouteMaxAggregateInputType
}

export type PatrolRouteGroupByOutputType = {
  id: string
  siteId: string
  name: string
  _count: PatrolRouteCountAggregateOutputType | null
  _min: PatrolRouteMinAggregateOutputType | null
  _max: PatrolRouteMaxAggregateOutputType | null
}

type GetPatrolRouteGroupByPayload<T extends PatrolRouteGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PatrolRouteGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PatrolRouteGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PatrolRouteGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PatrolRouteGroupByOutputType[P]>
      }
    >
  >



export type PatrolRouteWhereInput = {
  AND?: Prisma.PatrolRouteWhereInput | Prisma.PatrolRouteWhereInput[]
  OR?: Prisma.PatrolRouteWhereInput[]
  NOT?: Prisma.PatrolRouteWhereInput | Prisma.PatrolRouteWhereInput[]
  id?: Prisma.StringFilter<"PatrolRoute"> | string
  siteId?: Prisma.StringFilter<"PatrolRoute"> | string
  name?: Prisma.StringFilter<"PatrolRoute"> | string
  site?: Prisma.XOR<Prisma.SiteScalarRelationFilter, Prisma.SiteWhereInput>
  patrolPoints?: Prisma.PatrolPointListRelationFilter
}

export type PatrolRouteOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  siteId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  site?: Prisma.SiteOrderByWithRelationInput
  patrolPoints?: Prisma.PatrolPointOrderByRelationAggregateInput
}

export type PatrolRouteWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PatrolRouteWhereInput | Prisma.PatrolRouteWhereInput[]
  OR?: Prisma.PatrolRouteWhereInput[]
  NOT?: Prisma.PatrolRouteWhereInput | Prisma.PatrolRouteWhereInput[]
  siteId?: Prisma.StringFilter<"PatrolRoute"> | string
  name?: Prisma.StringFilter<"PatrolRoute"> | string
  site?: Prisma.XOR<Prisma.SiteScalarRelationFilter, Prisma.SiteWhereInput>
  patrolPoints?: Prisma.PatrolPointListRelationFilter
}, "id">

export type PatrolRouteOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  siteId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  _count?: Prisma.PatrolRouteCountOrderByAggregateInput
  _max?: Prisma.PatrolRouteMaxOrderByAggregateInput
  _min?: Prisma.PatrolRouteMinOrderByAggregateInput
}

export type PatrolRouteScalarWhereWithAggregatesInput = {
  AND?: Prisma.PatrolRouteScalarWhereWithAggregatesInput | Prisma.PatrolRouteScalarWhereWithAggregatesInput[]
  OR?: Prisma.PatrolRouteScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PatrolRouteScalarWhereWithAggregatesInput | Prisma.PatrolRouteScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PatrolRoute"> | string
  siteId?: Prisma.StringWithAggregatesFilter<"PatrolRoute"> | string
  name?: Prisma.StringWithAggregatesFilter<"PatrolRoute"> | string
}

export type PatrolRouteCreateInput = {
  id?: string
  name: string
  site: Prisma.SiteCreateNestedOneWithoutPatrolRoutesInput
  patrolPoints?: Prisma.PatrolPointCreateNestedManyWithoutPatrolRouteInput
}

export type PatrolRouteUncheckedCreateInput = {
  id?: string
  siteId: string
  name: string
  patrolPoints?: Prisma.PatrolPointUncheckedCreateNestedManyWithoutPatrolRouteInput
}

export type PatrolRouteUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  site?: Prisma.SiteUpdateOneRequiredWithoutPatrolRoutesNestedInput
  patrolPoints?: Prisma.PatrolPointUpdateManyWithoutPatrolRouteNestedInput
}

export type PatrolRouteUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  siteId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  patrolPoints?: Prisma.PatrolPointUncheckedUpdateManyWithoutPatrolRouteNestedInput
}

export type PatrolRouteCreateManyInput = {
  id?: string
  siteId: string
  name: string
}

export type PatrolRouteUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PatrolRouteUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  siteId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PatrolRouteListRelationFilter = {
  every?: Prisma.PatrolRouteWhereInput
  some?: Prisma.PatrolRouteWhereInput
  none?: Prisma.PatrolRouteWhereInput
}

export type PatrolRouteOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PatrolRouteCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  siteId?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type PatrolRouteMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  siteId?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type PatrolRouteMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  siteId?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type PatrolRouteScalarRelationFilter = {
  is?: Prisma.PatrolRouteWhereInput
  isNot?: Prisma.PatrolRouteWhereInput
}

export type PatrolRouteCreateNestedManyWithoutSiteInput = {
  create?: Prisma.XOR<Prisma.PatrolRouteCreateWithoutSiteInput, Prisma.PatrolRouteUncheckedCreateWithoutSiteInput> | Prisma.PatrolRouteCreateWithoutSiteInput[] | Prisma.PatrolRouteUncheckedCreateWithoutSiteInput[]
  connectOrCreate?: Prisma.PatrolRouteCreateOrConnectWithoutSiteInput | Prisma.PatrolRouteCreateOrConnectWithoutSiteInput[]
  createMany?: Prisma.PatrolRouteCreateManySiteInputEnvelope
  connect?: Prisma.PatrolRouteWhereUniqueInput | Prisma.PatrolRouteWhereUniqueInput[]
}

export type PatrolRouteUncheckedCreateNestedManyWithoutSiteInput = {
  create?: Prisma.XOR<Prisma.PatrolRouteCreateWithoutSiteInput, Prisma.PatrolRouteUncheckedCreateWithoutSiteInput> | Prisma.PatrolRouteCreateWithoutSiteInput[] | Prisma.PatrolRouteUncheckedCreateWithoutSiteInput[]
  connectOrCreate?: Prisma.PatrolRouteCreateOrConnectWithoutSiteInput | Prisma.PatrolRouteCreateOrConnectWithoutSiteInput[]
  createMany?: Prisma.PatrolRouteCreateManySiteInputEnvelope
  connect?: Prisma.PatrolRouteWhereUniqueInput | Prisma.PatrolRouteWhereUniqueInput[]
}

export type PatrolRouteUpdateManyWithoutSiteNestedInput = {
  create?: Prisma.XOR<Prisma.PatrolRouteCreateWithoutSiteInput, Prisma.PatrolRouteUncheckedCreateWithoutSiteInput> | Prisma.PatrolRouteCreateWithoutSiteInput[] | Prisma.PatrolRouteUncheckedCreateWithoutSiteInput[]
  connectOrCreate?: Prisma.PatrolRouteCreateOrConnectWithoutSiteInput | Prisma.PatrolRouteCreateOrConnectWithoutSiteInput[]
  upsert?: Prisma.PatrolRouteUpsertWithWhereUniqueWithoutSiteInput | Prisma.PatrolRouteUpsertWithWhereUniqueWithoutSiteInput[]
  createMany?: Prisma.PatrolRouteCreateManySiteInputEnvelope
  set?: Prisma.PatrolRouteWhereUniqueInput | Prisma.PatrolRouteWhereUniqueInput[]
  disconnect?: Prisma.PatrolRouteWhereUniqueInput | Prisma.PatrolRouteWhereUniqueInput[]
  delete?: Prisma.PatrolRouteWhereUniqueInput | Prisma.PatrolRouteWhereUniqueInput[]
  connect?: Prisma.PatrolRouteWhereUniqueInput | Prisma.PatrolRouteWhereUniqueInput[]
  update?: Prisma.PatrolRouteUpdateWithWhereUniqueWithoutSiteInput | Prisma.PatrolRouteUpdateWithWhereUniqueWithoutSiteInput[]
  updateMany?: Prisma.PatrolRouteUpdateManyWithWhereWithoutSiteInput | Prisma.PatrolRouteUpdateManyWithWhereWithoutSiteInput[]
  deleteMany?: Prisma.PatrolRouteScalarWhereInput | Prisma.PatrolRouteScalarWhereInput[]
}

export type PatrolRouteUncheckedUpdateManyWithoutSiteNestedInput = {
  create?: Prisma.XOR<Prisma.PatrolRouteCreateWithoutSiteInput, Prisma.PatrolRouteUncheckedCreateWithoutSiteInput> | Prisma.PatrolRouteCreateWithoutSiteInput[] | Prisma.PatrolRouteUncheckedCreateWithoutSiteInput[]
  connectOrCreate?: Prisma.PatrolRouteCreateOrConnectWithoutSiteInput | Prisma.PatrolRouteCreateOrConnectWithoutSiteInput[]
  upsert?: Prisma.PatrolRouteUpsertWithWhereUniqueWithoutSiteInput | Prisma.PatrolRouteUpsertWithWhereUniqueWithoutSiteInput[]
  createMany?: Prisma.PatrolRouteCreateManySiteInputEnvelope
  set?: Prisma.PatrolRouteWhereUniqueInput | Prisma.PatrolRouteWhereUniqueInput[]
  disconnect?: Prisma.PatrolRouteWhereUniqueInput | Prisma.PatrolRouteWhereUniqueInput[]
  delete?: Prisma.PatrolRouteWhereUniqueInput | Prisma.PatrolRouteWhereUniqueInput[]
  connect?: Prisma.PatrolRouteWhereUniqueInput | Prisma.PatrolRouteWhereUniqueInput[]
  update?: Prisma.PatrolRouteUpdateWithWhereUniqueWithoutSiteInput | Prisma.PatrolRouteUpdateWithWhereUniqueWithoutSiteInput[]
  updateMany?: Prisma.PatrolRouteUpdateManyWithWhereWithoutSiteInput | Prisma.PatrolRouteUpdateManyWithWhereWithoutSiteInput[]
  deleteMany?: Prisma.PatrolRouteScalarWhereInput | Prisma.PatrolRouteScalarWhereInput[]
}

export type PatrolRouteCreateNestedOneWithoutPatrolPointsInput = {
  create?: Prisma.XOR<Prisma.PatrolRouteCreateWithoutPatrolPointsInput, Prisma.PatrolRouteUncheckedCreateWithoutPatrolPointsInput>
  connectOrCreate?: Prisma.PatrolRouteCreateOrConnectWithoutPatrolPointsInput
  connect?: Prisma.PatrolRouteWhereUniqueInput
}

export type PatrolRouteUpdateOneRequiredWithoutPatrolPointsNestedInput = {
  create?: Prisma.XOR<Prisma.PatrolRouteCreateWithoutPatrolPointsInput, Prisma.PatrolRouteUncheckedCreateWithoutPatrolPointsInput>
  connectOrCreate?: Prisma.PatrolRouteCreateOrConnectWithoutPatrolPointsInput
  upsert?: Prisma.PatrolRouteUpsertWithoutPatrolPointsInput
  connect?: Prisma.PatrolRouteWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PatrolRouteUpdateToOneWithWhereWithoutPatrolPointsInput, Prisma.PatrolRouteUpdateWithoutPatrolPointsInput>, Prisma.PatrolRouteUncheckedUpdateWithoutPatrolPointsInput>
}

export type PatrolRouteCreateWithoutSiteInput = {
  id?: string
  name: string
  patrolPoints?: Prisma.PatrolPointCreateNestedManyWithoutPatrolRouteInput
}

export type PatrolRouteUncheckedCreateWithoutSiteInput = {
  id?: string
  name: string
  patrolPoints?: Prisma.PatrolPointUncheckedCreateNestedManyWithoutPatrolRouteInput
}

export type PatrolRouteCreateOrConnectWithoutSiteInput = {
  where: Prisma.PatrolRouteWhereUniqueInput
  create: Prisma.XOR<Prisma.PatrolRouteCreateWithoutSiteInput, Prisma.PatrolRouteUncheckedCreateWithoutSiteInput>
}

export type PatrolRouteCreateManySiteInputEnvelope = {
  data: Prisma.PatrolRouteCreateManySiteInput | Prisma.PatrolRouteCreateManySiteInput[]
  skipDuplicates?: boolean
}

export type PatrolRouteUpsertWithWhereUniqueWithoutSiteInput = {
  where: Prisma.PatrolRouteWhereUniqueInput
  update: Prisma.XOR<Prisma.PatrolRouteUpdateWithoutSiteInput, Prisma.PatrolRouteUncheckedUpdateWithoutSiteInput>
  create: Prisma.XOR<Prisma.PatrolRouteCreateWithoutSiteInput, Prisma.PatrolRouteUncheckedCreateWithoutSiteInput>
}

export type PatrolRouteUpdateWithWhereUniqueWithoutSiteInput = {
  where: Prisma.PatrolRouteWhereUniqueInput
  data: Prisma.XOR<Prisma.PatrolRouteUpdateWithoutSiteInput, Prisma.PatrolRouteUncheckedUpdateWithoutSiteInput>
}

export type PatrolRouteUpdateManyWithWhereWithoutSiteInput = {
  where: Prisma.PatrolRouteScalarWhereInput
  data: Prisma.XOR<Prisma.PatrolRouteUpdateManyMutationInput, Prisma.PatrolRouteUncheckedUpdateManyWithoutSiteInput>
}

export type PatrolRouteScalarWhereInput = {
  AND?: Prisma.PatrolRouteScalarWhereInput | Prisma.PatrolRouteScalarWhereInput[]
  OR?: Prisma.PatrolRouteScalarWhereInput[]
  NOT?: Prisma.PatrolRouteScalarWhereInput | Prisma.PatrolRouteScalarWhereInput[]
  id?: Prisma.StringFilter<"PatrolRoute"> | string
  siteId?: Prisma.StringFilter<"PatrolRoute"> | string
  name?: Prisma.StringFilter<"PatrolRoute"> | string
}

export type PatrolRouteCreateWithoutPatrolPointsInput = {
  id?: string
  name: string
  site: Prisma.SiteCreateNestedOneWithoutPatrolRoutesInput
}

export type PatrolRouteUncheckedCreateWithoutPatrolPointsInput = {
  id?: string
  siteId: string
  name: string
}

export type PatrolRouteCreateOrConnectWithoutPatrolPointsInput = {
  where: Prisma.PatrolRouteWhereUniqueInput
  create: Prisma.XOR<Prisma.PatrolRouteCreateWithoutPatrolPointsInput, Prisma.PatrolRouteUncheckedCreateWithoutPatrolPointsInput>
}

export type PatrolRouteUpsertWithoutPatrolPointsInput = {
  update: Prisma.XOR<Prisma.PatrolRouteUpdateWithoutPatrolPointsInput, Prisma.PatrolRouteUncheckedUpdateWithoutPatrolPointsInput>
  create: Prisma.XOR<Prisma.PatrolRouteCreateWithoutPatrolPointsInput, Prisma.PatrolRouteUncheckedCreateWithoutPatrolPointsInput>
  where?: Prisma.PatrolRouteWhereInput
}

export type PatrolRouteUpdateToOneWithWhereWithoutPatrolPointsInput = {
  where?: Prisma.PatrolRouteWhereInput
  data: Prisma.XOR<Prisma.PatrolRouteUpdateWithoutPatrolPointsInput, Prisma.PatrolRouteUncheckedUpdateWithoutPatrolPointsInput>
}

export type PatrolRouteUpdateWithoutPatrolPointsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  site?: Prisma.SiteUpdateOneRequiredWithoutPatrolRoutesNestedInput
}

export type PatrolRouteUncheckedUpdateWithoutPatrolPointsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  siteId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PatrolRouteCreateManySiteInput = {
  id?: string
  name: string
}

export type PatrolRouteUpdateWithoutSiteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  patrolPoints?: Prisma.PatrolPointUpdateManyWithoutPatrolRouteNestedInput
}

export type PatrolRouteUncheckedUpdateWithoutSiteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  patrolPoints?: Prisma.PatrolPointUncheckedUpdateManyWithoutPatrolRouteNestedInput
}

export type PatrolRouteUncheckedUpdateManyWithoutSiteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type PatrolRouteCountOutputType
 */

export type PatrolRouteCountOutputType = {
  patrolPoints: number
}

export type PatrolRouteCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  patrolPoints?: boolean | PatrolRouteCountOutputTypeCountPatrolPointsArgs
}

/**
 * PatrolRouteCountOutputType without action
 */
export type PatrolRouteCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolRouteCountOutputType
   */
  select?: Prisma.PatrolRouteCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PatrolRouteCountOutputType without action
 */
export type PatrolRouteCountOutputTypeCountPatrolPointsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PatrolPointWhereInput
}


export type PatrolRouteSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  siteId?: boolean
  name?: boolean
  site?: boolean | Prisma.SiteDefaultArgs<ExtArgs>
  patrolPoints?: boolean | Prisma.PatrolRoute$patrolPointsArgs<ExtArgs>
  _count?: boolean | Prisma.PatrolRouteCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["patrolRoute"]>

export type PatrolRouteSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  siteId?: boolean
  name?: boolean
  site?: boolean | Prisma.SiteDefaultArgs<ExtArgs>
}, ExtArgs["result"]["patrolRoute"]>

export type PatrolRouteSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  siteId?: boolean
  name?: boolean
  site?: boolean | Prisma.SiteDefaultArgs<ExtArgs>
}, ExtArgs["result"]["patrolRoute"]>

export type PatrolRouteSelectScalar = {
  id?: boolean
  siteId?: boolean
  name?: boolean
}

export type PatrolRouteOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "siteId" | "name", ExtArgs["result"]["patrolRoute"]>
export type PatrolRouteInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  site?: boolean | Prisma.SiteDefaultArgs<ExtArgs>
  patrolPoints?: boolean | Prisma.PatrolRoute$patrolPointsArgs<ExtArgs>
  _count?: boolean | Prisma.PatrolRouteCountOutputTypeDefaultArgs<ExtArgs>
}
export type PatrolRouteIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  site?: boolean | Prisma.SiteDefaultArgs<ExtArgs>
}
export type PatrolRouteIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  site?: boolean | Prisma.SiteDefaultArgs<ExtArgs>
}

export type $PatrolRoutePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PatrolRoute"
  objects: {
    site: Prisma.$SitePayload<ExtArgs>
    patrolPoints: Prisma.$PatrolPointPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    siteId: string
    name: string
  }, ExtArgs["result"]["patrolRoute"]>
  composites: {}
}

export type PatrolRouteGetPayload<S extends boolean | null | undefined | PatrolRouteDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PatrolRoutePayload, S>

export type PatrolRouteCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PatrolRouteFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PatrolRouteCountAggregateInputType | true
  }

export interface PatrolRouteDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PatrolRoute'], meta: { name: 'PatrolRoute' } }
  /**
   * Find zero or one PatrolRoute that matches the filter.
   * @param {PatrolRouteFindUniqueArgs} args - Arguments to find a PatrolRoute
   * @example
   * // Get one PatrolRoute
   * const patrolRoute = await prisma.patrolRoute.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PatrolRouteFindUniqueArgs>(args: Prisma.SelectSubset<T, PatrolRouteFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PatrolRouteClient<runtime.Types.Result.GetResult<Prisma.$PatrolRoutePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PatrolRoute that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PatrolRouteFindUniqueOrThrowArgs} args - Arguments to find a PatrolRoute
   * @example
   * // Get one PatrolRoute
   * const patrolRoute = await prisma.patrolRoute.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PatrolRouteFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PatrolRouteFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PatrolRouteClient<runtime.Types.Result.GetResult<Prisma.$PatrolRoutePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PatrolRoute that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PatrolRouteFindFirstArgs} args - Arguments to find a PatrolRoute
   * @example
   * // Get one PatrolRoute
   * const patrolRoute = await prisma.patrolRoute.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PatrolRouteFindFirstArgs>(args?: Prisma.SelectSubset<T, PatrolRouteFindFirstArgs<ExtArgs>>): Prisma.Prisma__PatrolRouteClient<runtime.Types.Result.GetResult<Prisma.$PatrolRoutePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PatrolRoute that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PatrolRouteFindFirstOrThrowArgs} args - Arguments to find a PatrolRoute
   * @example
   * // Get one PatrolRoute
   * const patrolRoute = await prisma.patrolRoute.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PatrolRouteFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PatrolRouteFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PatrolRouteClient<runtime.Types.Result.GetResult<Prisma.$PatrolRoutePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PatrolRoutes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PatrolRouteFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PatrolRoutes
   * const patrolRoutes = await prisma.patrolRoute.findMany()
   * 
   * // Get first 10 PatrolRoutes
   * const patrolRoutes = await prisma.patrolRoute.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const patrolRouteWithIdOnly = await prisma.patrolRoute.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PatrolRouteFindManyArgs>(args?: Prisma.SelectSubset<T, PatrolRouteFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PatrolRoutePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PatrolRoute.
   * @param {PatrolRouteCreateArgs} args - Arguments to create a PatrolRoute.
   * @example
   * // Create one PatrolRoute
   * const PatrolRoute = await prisma.patrolRoute.create({
   *   data: {
   *     // ... data to create a PatrolRoute
   *   }
   * })
   * 
   */
  create<T extends PatrolRouteCreateArgs>(args: Prisma.SelectSubset<T, PatrolRouteCreateArgs<ExtArgs>>): Prisma.Prisma__PatrolRouteClient<runtime.Types.Result.GetResult<Prisma.$PatrolRoutePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PatrolRoutes.
   * @param {PatrolRouteCreateManyArgs} args - Arguments to create many PatrolRoutes.
   * @example
   * // Create many PatrolRoutes
   * const patrolRoute = await prisma.patrolRoute.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PatrolRouteCreateManyArgs>(args?: Prisma.SelectSubset<T, PatrolRouteCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PatrolRoutes and returns the data saved in the database.
   * @param {PatrolRouteCreateManyAndReturnArgs} args - Arguments to create many PatrolRoutes.
   * @example
   * // Create many PatrolRoutes
   * const patrolRoute = await prisma.patrolRoute.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PatrolRoutes and only return the `id`
   * const patrolRouteWithIdOnly = await prisma.patrolRoute.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PatrolRouteCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PatrolRouteCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PatrolRoutePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PatrolRoute.
   * @param {PatrolRouteDeleteArgs} args - Arguments to delete one PatrolRoute.
   * @example
   * // Delete one PatrolRoute
   * const PatrolRoute = await prisma.patrolRoute.delete({
   *   where: {
   *     // ... filter to delete one PatrolRoute
   *   }
   * })
   * 
   */
  delete<T extends PatrolRouteDeleteArgs>(args: Prisma.SelectSubset<T, PatrolRouteDeleteArgs<ExtArgs>>): Prisma.Prisma__PatrolRouteClient<runtime.Types.Result.GetResult<Prisma.$PatrolRoutePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PatrolRoute.
   * @param {PatrolRouteUpdateArgs} args - Arguments to update one PatrolRoute.
   * @example
   * // Update one PatrolRoute
   * const patrolRoute = await prisma.patrolRoute.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PatrolRouteUpdateArgs>(args: Prisma.SelectSubset<T, PatrolRouteUpdateArgs<ExtArgs>>): Prisma.Prisma__PatrolRouteClient<runtime.Types.Result.GetResult<Prisma.$PatrolRoutePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PatrolRoutes.
   * @param {PatrolRouteDeleteManyArgs} args - Arguments to filter PatrolRoutes to delete.
   * @example
   * // Delete a few PatrolRoutes
   * const { count } = await prisma.patrolRoute.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PatrolRouteDeleteManyArgs>(args?: Prisma.SelectSubset<T, PatrolRouteDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PatrolRoutes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PatrolRouteUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PatrolRoutes
   * const patrolRoute = await prisma.patrolRoute.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PatrolRouteUpdateManyArgs>(args: Prisma.SelectSubset<T, PatrolRouteUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PatrolRoutes and returns the data updated in the database.
   * @param {PatrolRouteUpdateManyAndReturnArgs} args - Arguments to update many PatrolRoutes.
   * @example
   * // Update many PatrolRoutes
   * const patrolRoute = await prisma.patrolRoute.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PatrolRoutes and only return the `id`
   * const patrolRouteWithIdOnly = await prisma.patrolRoute.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PatrolRouteUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PatrolRouteUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PatrolRoutePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PatrolRoute.
   * @param {PatrolRouteUpsertArgs} args - Arguments to update or create a PatrolRoute.
   * @example
   * // Update or create a PatrolRoute
   * const patrolRoute = await prisma.patrolRoute.upsert({
   *   create: {
   *     // ... data to create a PatrolRoute
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PatrolRoute we want to update
   *   }
   * })
   */
  upsert<T extends PatrolRouteUpsertArgs>(args: Prisma.SelectSubset<T, PatrolRouteUpsertArgs<ExtArgs>>): Prisma.Prisma__PatrolRouteClient<runtime.Types.Result.GetResult<Prisma.$PatrolRoutePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PatrolRoutes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PatrolRouteCountArgs} args - Arguments to filter PatrolRoutes to count.
   * @example
   * // Count the number of PatrolRoutes
   * const count = await prisma.patrolRoute.count({
   *   where: {
   *     // ... the filter for the PatrolRoutes we want to count
   *   }
   * })
  **/
  count<T extends PatrolRouteCountArgs>(
    args?: Prisma.Subset<T, PatrolRouteCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PatrolRouteCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PatrolRoute.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PatrolRouteAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PatrolRouteAggregateArgs>(args: Prisma.Subset<T, PatrolRouteAggregateArgs>): Prisma.PrismaPromise<GetPatrolRouteAggregateType<T>>

  /**
   * Group by PatrolRoute.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PatrolRouteGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PatrolRouteGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PatrolRouteGroupByArgs['orderBy'] }
      : { orderBy?: PatrolRouteGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PatrolRouteGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPatrolRouteGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PatrolRoute model
 */
readonly fields: PatrolRouteFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PatrolRoute.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PatrolRouteClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  site<T extends Prisma.SiteDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SiteDefaultArgs<ExtArgs>>): Prisma.Prisma__SiteClient<runtime.Types.Result.GetResult<Prisma.$SitePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  patrolPoints<T extends Prisma.PatrolRoute$patrolPointsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PatrolRoute$patrolPointsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PatrolPointPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PatrolRoute model
 */
export interface PatrolRouteFieldRefs {
  readonly id: Prisma.FieldRef<"PatrolRoute", 'String'>
  readonly siteId: Prisma.FieldRef<"PatrolRoute", 'String'>
  readonly name: Prisma.FieldRef<"PatrolRoute", 'String'>
}
    

// Custom InputTypes
/**
 * PatrolRoute findUnique
 */
export type PatrolRouteFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolRoute
   */
  select?: Prisma.PatrolRouteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolRoute
   */
  omit?: Prisma.PatrolRouteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolRouteInclude<ExtArgs> | null
  /**
   * Filter, which PatrolRoute to fetch.
   */
  where: Prisma.PatrolRouteWhereUniqueInput
}

/**
 * PatrolRoute findUniqueOrThrow
 */
export type PatrolRouteFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolRoute
   */
  select?: Prisma.PatrolRouteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolRoute
   */
  omit?: Prisma.PatrolRouteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolRouteInclude<ExtArgs> | null
  /**
   * Filter, which PatrolRoute to fetch.
   */
  where: Prisma.PatrolRouteWhereUniqueInput
}

/**
 * PatrolRoute findFirst
 */
export type PatrolRouteFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolRoute
   */
  select?: Prisma.PatrolRouteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolRoute
   */
  omit?: Prisma.PatrolRouteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolRouteInclude<ExtArgs> | null
  /**
   * Filter, which PatrolRoute to fetch.
   */
  where?: Prisma.PatrolRouteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PatrolRoutes to fetch.
   */
  orderBy?: Prisma.PatrolRouteOrderByWithRelationInput | Prisma.PatrolRouteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PatrolRoutes.
   */
  cursor?: Prisma.PatrolRouteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PatrolRoutes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PatrolRoutes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PatrolRoutes.
   */
  distinct?: Prisma.PatrolRouteScalarFieldEnum | Prisma.PatrolRouteScalarFieldEnum[]
}

/**
 * PatrolRoute findFirstOrThrow
 */
export type PatrolRouteFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolRoute
   */
  select?: Prisma.PatrolRouteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolRoute
   */
  omit?: Prisma.PatrolRouteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolRouteInclude<ExtArgs> | null
  /**
   * Filter, which PatrolRoute to fetch.
   */
  where?: Prisma.PatrolRouteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PatrolRoutes to fetch.
   */
  orderBy?: Prisma.PatrolRouteOrderByWithRelationInput | Prisma.PatrolRouteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PatrolRoutes.
   */
  cursor?: Prisma.PatrolRouteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PatrolRoutes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PatrolRoutes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PatrolRoutes.
   */
  distinct?: Prisma.PatrolRouteScalarFieldEnum | Prisma.PatrolRouteScalarFieldEnum[]
}

/**
 * PatrolRoute findMany
 */
export type PatrolRouteFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolRoute
   */
  select?: Prisma.PatrolRouteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolRoute
   */
  omit?: Prisma.PatrolRouteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolRouteInclude<ExtArgs> | null
  /**
   * Filter, which PatrolRoutes to fetch.
   */
  where?: Prisma.PatrolRouteWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PatrolRoutes to fetch.
   */
  orderBy?: Prisma.PatrolRouteOrderByWithRelationInput | Prisma.PatrolRouteOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PatrolRoutes.
   */
  cursor?: Prisma.PatrolRouteWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PatrolRoutes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PatrolRoutes.
   */
  skip?: number
  distinct?: Prisma.PatrolRouteScalarFieldEnum | Prisma.PatrolRouteScalarFieldEnum[]
}

/**
 * PatrolRoute create
 */
export type PatrolRouteCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolRoute
   */
  select?: Prisma.PatrolRouteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolRoute
   */
  omit?: Prisma.PatrolRouteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolRouteInclude<ExtArgs> | null
  /**
   * The data needed to create a PatrolRoute.
   */
  data: Prisma.XOR<Prisma.PatrolRouteCreateInput, Prisma.PatrolRouteUncheckedCreateInput>
}

/**
 * PatrolRoute createMany
 */
export type PatrolRouteCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PatrolRoutes.
   */
  data: Prisma.PatrolRouteCreateManyInput | Prisma.PatrolRouteCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PatrolRoute createManyAndReturn
 */
export type PatrolRouteCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolRoute
   */
  select?: Prisma.PatrolRouteSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolRoute
   */
  omit?: Prisma.PatrolRouteOmit<ExtArgs> | null
  /**
   * The data used to create many PatrolRoutes.
   */
  data: Prisma.PatrolRouteCreateManyInput | Prisma.PatrolRouteCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolRouteIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PatrolRoute update
 */
export type PatrolRouteUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolRoute
   */
  select?: Prisma.PatrolRouteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolRoute
   */
  omit?: Prisma.PatrolRouteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolRouteInclude<ExtArgs> | null
  /**
   * The data needed to update a PatrolRoute.
   */
  data: Prisma.XOR<Prisma.PatrolRouteUpdateInput, Prisma.PatrolRouteUncheckedUpdateInput>
  /**
   * Choose, which PatrolRoute to update.
   */
  where: Prisma.PatrolRouteWhereUniqueInput
}

/**
 * PatrolRoute updateMany
 */
export type PatrolRouteUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PatrolRoutes.
   */
  data: Prisma.XOR<Prisma.PatrolRouteUpdateManyMutationInput, Prisma.PatrolRouteUncheckedUpdateManyInput>
  /**
   * Filter which PatrolRoutes to update
   */
  where?: Prisma.PatrolRouteWhereInput
  /**
   * Limit how many PatrolRoutes to update.
   */
  limit?: number
}

/**
 * PatrolRoute updateManyAndReturn
 */
export type PatrolRouteUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolRoute
   */
  select?: Prisma.PatrolRouteSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolRoute
   */
  omit?: Prisma.PatrolRouteOmit<ExtArgs> | null
  /**
   * The data used to update PatrolRoutes.
   */
  data: Prisma.XOR<Prisma.PatrolRouteUpdateManyMutationInput, Prisma.PatrolRouteUncheckedUpdateManyInput>
  /**
   * Filter which PatrolRoutes to update
   */
  where?: Prisma.PatrolRouteWhereInput
  /**
   * Limit how many PatrolRoutes to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolRouteIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PatrolRoute upsert
 */
export type PatrolRouteUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolRoute
   */
  select?: Prisma.PatrolRouteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolRoute
   */
  omit?: Prisma.PatrolRouteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolRouteInclude<ExtArgs> | null
  /**
   * The filter to search for the PatrolRoute to update in case it exists.
   */
  where: Prisma.PatrolRouteWhereUniqueInput
  /**
   * In case the PatrolRoute found by the `where` argument doesn't exist, create a new PatrolRoute with this data.
   */
  create: Prisma.XOR<Prisma.PatrolRouteCreateInput, Prisma.PatrolRouteUncheckedCreateInput>
  /**
   * In case the PatrolRoute was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PatrolRouteUpdateInput, Prisma.PatrolRouteUncheckedUpdateInput>
}

/**
 * PatrolRoute delete
 */
export type PatrolRouteDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolRoute
   */
  select?: Prisma.PatrolRouteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolRoute
   */
  omit?: Prisma.PatrolRouteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolRouteInclude<ExtArgs> | null
  /**
   * Filter which PatrolRoute to delete.
   */
  where: Prisma.PatrolRouteWhereUniqueInput
}

/**
 * PatrolRoute deleteMany
 */
export type PatrolRouteDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PatrolRoutes to delete
   */
  where?: Prisma.PatrolRouteWhereInput
  /**
   * Limit how many PatrolRoutes to delete.
   */
  limit?: number
}

/**
 * PatrolRoute.patrolPoints
 */
export type PatrolRoute$patrolPointsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolPoint
   */
  select?: Prisma.PatrolPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolPoint
   */
  omit?: Prisma.PatrolPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolPointInclude<ExtArgs> | null
  where?: Prisma.PatrolPointWhereInput
  orderBy?: Prisma.PatrolPointOrderByWithRelationInput | Prisma.PatrolPointOrderByWithRelationInput[]
  cursor?: Prisma.PatrolPointWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PatrolPointScalarFieldEnum | Prisma.PatrolPointScalarFieldEnum[]
}

/**
 * PatrolRoute without action
 */
export type PatrolRouteDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolRoute
   */
  select?: Prisma.PatrolRouteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolRoute
   */
  omit?: Prisma.PatrolRouteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolRouteInclude<ExtArgs> | null
}
