
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PatrolPoint` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model PatrolPoint
 * 
 */
export type PatrolPointModel = runtime.Types.Result.DefaultSelection<Prisma.$PatrolPointPayload>

export type AggregatePatrolPoint = {
  _count: PatrolPointCountAggregateOutputType | null
  _min: PatrolPointMinAggregateOutputType | null
  _max: PatrolPointMaxAggregateOutputType | null
}

export type PatrolPointMinAggregateOutputType = {
  id: string | null
  patrolRouteId: string | null
  label: string | null
  qrCodeValue: string | null
}

export type PatrolPointMaxAggregateOutputType = {
  id: string | null
  patrolRouteId: string | null
  label: string | null
  qrCodeValue: string | null
}

export type PatrolPointCountAggregateOutputType = {
  id: number
  patrolRouteId: number
  label: number
  qrCodeValue: number
  _all: number
}


export type PatrolPointMinAggregateInputType = {
  id?: true
  patrolRouteId?: true
  label?: true
  qrCodeValue?: true
}

export type PatrolPointMaxAggregateInputType = {
  id?: true
  patrolRouteId?: true
  label?: true
  qrCodeValue?: true
}

export type PatrolPointCountAggregateInputType = {
  id?: true
  patrolRouteId?: true
  label?: true
  qrCodeValue?: true
  _all?: true
}

export type PatrolPointAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PatrolPoint to aggregate.
   */
  where?: Prisma.PatrolPointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PatrolPoints to fetch.
   */
  orderBy?: Prisma.PatrolPointOrderByWithRelationInput | Prisma.PatrolPointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PatrolPointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PatrolPoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PatrolPoints.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PatrolPoints
  **/
  _count?: true | PatrolPointCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PatrolPointMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PatrolPointMaxAggregateInputType
}

export type GetPatrolPointAggregateType<T extends PatrolPointAggregateArgs> = {
      [P in keyof T & keyof AggregatePatrolPoint]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePatrolPoint[P]>
    : Prisma.GetScalarType<T[P], AggregatePatrolPoint[P]>
}




export type PatrolPointGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PatrolPointWhereInput
  orderBy?: Prisma.PatrolPointOrderByWithAggregationInput | Prisma.PatrolPointOrderByWithAggregationInput[]
  by: Prisma.PatrolPointScalarFieldEnum[] | Prisma.PatrolPointScalarFieldEnum
  having?: Prisma.PatrolPointScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PatrolPointCountAggregateInputType | true
  _min?: PatrolPointMinAggregateInputType
  _max?: PatrolPointMaxAggregateInputType
}

export type PatrolPointGroupByOutputType = {
  id: string
  patrolRouteId: string
  label: string
  qrCodeValue: string
  _count: PatrolPointCountAggregateOutputType | null
  _min: PatrolPointMinAggregateOutputType | null
  _max: PatrolPointMaxAggregateOutputType | null
}

type GetPatrolPointGroupByPayload<T extends PatrolPointGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PatrolPointGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PatrolPointGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PatrolPointGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PatrolPointGroupByOutputType[P]>
      }
    >
  >



export type PatrolPointWhereInput = {
  AND?: Prisma.PatrolPointWhereInput | Prisma.PatrolPointWhereInput[]
  OR?: Prisma.PatrolPointWhereInput[]
  NOT?: Prisma.PatrolPointWhereInput | Prisma.PatrolPointWhereInput[]
  id?: Prisma.StringFilter<"PatrolPoint"> | string
  patrolRouteId?: Prisma.StringFilter<"PatrolPoint"> | string
  label?: Prisma.StringFilter<"PatrolPoint"> | string
  qrCodeValue?: Prisma.StringFilter<"PatrolPoint"> | string
  patrolRoute?: Prisma.XOR<Prisma.PatrolRouteScalarRelationFilter, Prisma.PatrolRouteWhereInput>
  patrolLogs?: Prisma.PatrolLogListRelationFilter
}

export type PatrolPointOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  patrolRouteId?: Prisma.SortOrder
  label?: Prisma.SortOrder
  qrCodeValue?: Prisma.SortOrder
  patrolRoute?: Prisma.PatrolRouteOrderByWithRelationInput
  patrolLogs?: Prisma.PatrolLogOrderByRelationAggregateInput
}

export type PatrolPointWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  qrCodeValue?: string
  AND?: Prisma.PatrolPointWhereInput | Prisma.PatrolPointWhereInput[]
  OR?: Prisma.PatrolPointWhereInput[]
  NOT?: Prisma.PatrolPointWhereInput | Prisma.PatrolPointWhereInput[]
  patrolRouteId?: Prisma.StringFilter<"PatrolPoint"> | string
  label?: Prisma.StringFilter<"PatrolPoint"> | string
  patrolRoute?: Prisma.XOR<Prisma.PatrolRouteScalarRelationFilter, Prisma.PatrolRouteWhereInput>
  patrolLogs?: Prisma.PatrolLogListRelationFilter
}, "id" | "qrCodeValue">

export type PatrolPointOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  patrolRouteId?: Prisma.SortOrder
  label?: Prisma.SortOrder
  qrCodeValue?: Prisma.SortOrder
  _count?: Prisma.PatrolPointCountOrderByAggregateInput
  _max?: Prisma.PatrolPointMaxOrderByAggregateInput
  _min?: Prisma.PatrolPointMinOrderByAggregateInput
}

export type PatrolPointScalarWhereWithAggregatesInput = {
  AND?: Prisma.PatrolPointScalarWhereWithAggregatesInput | Prisma.PatrolPointScalarWhereWithAggregatesInput[]
  OR?: Prisma.PatrolPointScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PatrolPointScalarWhereWithAggregatesInput | Prisma.PatrolPointScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PatrolPoint"> | string
  patrolRouteId?: Prisma.StringWithAggregatesFilter<"PatrolPoint"> | string
  label?: Prisma.StringWithAggregatesFilter<"PatrolPoint"> | string
  qrCodeValue?: Prisma.StringWithAggregatesFilter<"PatrolPoint"> | string
}

export type PatrolPointCreateInput = {
  id?: string
  label: string
  qrCodeValue: string
  patrolRoute: Prisma.PatrolRouteCreateNestedOneWithoutPatrolPointsInput
  patrolLogs?: Prisma.PatrolLogCreateNestedManyWithoutPatrolPointInput
}

export type PatrolPointUncheckedCreateInput = {
  id?: string
  patrolRouteId: string
  label: string
  qrCodeValue: string
  patrolLogs?: Prisma.PatrolLogUncheckedCreateNestedManyWithoutPatrolPointInput
}

export type PatrolPointUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  qrCodeValue?: Prisma.StringFieldUpdateOperationsInput | string
  patrolRoute?: Prisma.PatrolRouteUpdateOneRequiredWithoutPatrolPointsNestedInput
  patrolLogs?: Prisma.PatrolLogUpdateManyWithoutPatrolPointNestedInput
}

export type PatrolPointUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  patrolRouteId?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  qrCodeValue?: Prisma.StringFieldUpdateOperationsInput | string
  patrolLogs?: Prisma.PatrolLogUncheckedUpdateManyWithoutPatrolPointNestedInput
}

export type PatrolPointCreateManyInput = {
  id?: string
  patrolRouteId: string
  label: string
  qrCodeValue: string
}

export type PatrolPointUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  qrCodeValue?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PatrolPointUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  patrolRouteId?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  qrCodeValue?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PatrolPointListRelationFilter = {
  every?: Prisma.PatrolPointWhereInput
  some?: Prisma.PatrolPointWhereInput
  none?: Prisma.PatrolPointWhereInput
}

export type PatrolPointOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PatrolPointCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  patrolRouteId?: Prisma.SortOrder
  label?: Prisma.SortOrder
  qrCodeValue?: Prisma.SortOrder
}

export type PatrolPointMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  patrolRouteId?: Prisma.SortOrder
  label?: Prisma.SortOrder
  qrCodeValue?: Prisma.SortOrder
}

export type PatrolPointMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  patrolRouteId?: Prisma.SortOrder
  label?: Prisma.SortOrder
  qrCodeValue?: Prisma.SortOrder
}

export type PatrolPointScalarRelationFilter = {
  is?: Prisma.PatrolPointWhereInput
  isNot?: Prisma.PatrolPointWhereInput
}

export type PatrolPointCreateNestedManyWithoutPatrolRouteInput = {
  create?: Prisma.XOR<Prisma.PatrolPointCreateWithoutPatrolRouteInput, Prisma.PatrolPointUncheckedCreateWithoutPatrolRouteInput> | Prisma.PatrolPointCreateWithoutPatrolRouteInput[] | Prisma.PatrolPointUncheckedCreateWithoutPatrolRouteInput[]
  connectOrCreate?: Prisma.PatrolPointCreateOrConnectWithoutPatrolRouteInput | Prisma.PatrolPointCreateOrConnectWithoutPatrolRouteInput[]
  createMany?: Prisma.PatrolPointCreateManyPatrolRouteInputEnvelope
  connect?: Prisma.PatrolPointWhereUniqueInput | Prisma.PatrolPointWhereUniqueInput[]
}

export type PatrolPointUncheckedCreateNestedManyWithoutPatrolRouteInput = {
  create?: Prisma.XOR<Prisma.PatrolPointCreateWithoutPatrolRouteInput, Prisma.PatrolPointUncheckedCreateWithoutPatrolRouteInput> | Prisma.PatrolPointCreateWithoutPatrolRouteInput[] | Prisma.PatrolPointUncheckedCreateWithoutPatrolRouteInput[]
  connectOrCreate?: Prisma.PatrolPointCreateOrConnectWithoutPatrolRouteInput | Prisma.PatrolPointCreateOrConnectWithoutPatrolRouteInput[]
  createMany?: Prisma.PatrolPointCreateManyPatrolRouteInputEnvelope
  connect?: Prisma.PatrolPointWhereUniqueInput | Prisma.PatrolPointWhereUniqueInput[]
}

export type PatrolPointUpdateManyWithoutPatrolRouteNestedInput = {
  create?: Prisma.XOR<Prisma.PatrolPointCreateWithoutPatrolRouteInput, Prisma.PatrolPointUncheckedCreateWithoutPatrolRouteInput> | Prisma.PatrolPointCreateWithoutPatrolRouteInput[] | Prisma.PatrolPointUncheckedCreateWithoutPatrolRouteInput[]
  connectOrCreate?: Prisma.PatrolPointCreateOrConnectWithoutPatrolRouteInput | Prisma.PatrolPointCreateOrConnectWithoutPatrolRouteInput[]
  upsert?: Prisma.PatrolPointUpsertWithWhereUniqueWithoutPatrolRouteInput | Prisma.PatrolPointUpsertWithWhereUniqueWithoutPatrolRouteInput[]
  createMany?: Prisma.PatrolPointCreateManyPatrolRouteInputEnvelope
  set?: Prisma.PatrolPointWhereUniqueInput | Prisma.PatrolPointWhereUniqueInput[]
  disconnect?: Prisma.PatrolPointWhereUniqueInput | Prisma.PatrolPointWhereUniqueInput[]
  delete?: Prisma.PatrolPointWhereUniqueInput | Prisma.PatrolPointWhereUniqueInput[]
  connect?: Prisma.PatrolPointWhereUniqueInput | Prisma.PatrolPointWhereUniqueInput[]
  update?: Prisma.PatrolPointUpdateWithWhereUniqueWithoutPatrolRouteInput | Prisma.PatrolPointUpdateWithWhereUniqueWithoutPatrolRouteInput[]
  updateMany?: Prisma.PatrolPointUpdateManyWithWhereWithoutPatrolRouteInput | Prisma.PatrolPointUpdateManyWithWhereWithoutPatrolRouteInput[]
  deleteMany?: Prisma.PatrolPointScalarWhereInput | Prisma.PatrolPointScalarWhereInput[]
}

export type PatrolPointUncheckedUpdateManyWithoutPatrolRouteNestedInput = {
  create?: Prisma.XOR<Prisma.PatrolPointCreateWithoutPatrolRouteInput, Prisma.PatrolPointUncheckedCreateWithoutPatrolRouteInput> | Prisma.PatrolPointCreateWithoutPatrolRouteInput[] | Prisma.PatrolPointUncheckedCreateWithoutPatrolRouteInput[]
  connectOrCreate?: Prisma.PatrolPointCreateOrConnectWithoutPatrolRouteInput | Prisma.PatrolPointCreateOrConnectWithoutPatrolRouteInput[]
  upsert?: Prisma.PatrolPointUpsertWithWhereUniqueWithoutPatrolRouteInput | Prisma.PatrolPointUpsertWithWhereUniqueWithoutPatrolRouteInput[]
  createMany?: Prisma.PatrolPointCreateManyPatrolRouteInputEnvelope
  set?: Prisma.PatrolPointWhereUniqueInput | Prisma.PatrolPointWhereUniqueInput[]
  disconnect?: Prisma.PatrolPointWhereUniqueInput | Prisma.PatrolPointWhereUniqueInput[]
  delete?: Prisma.PatrolPointWhereUniqueInput | Prisma.PatrolPointWhereUniqueInput[]
  connect?: Prisma.PatrolPointWhereUniqueInput | Prisma.PatrolPointWhereUniqueInput[]
  update?: Prisma.PatrolPointUpdateWithWhereUniqueWithoutPatrolRouteInput | Prisma.PatrolPointUpdateWithWhereUniqueWithoutPatrolRouteInput[]
  updateMany?: Prisma.PatrolPointUpdateManyWithWhereWithoutPatrolRouteInput | Prisma.PatrolPointUpdateManyWithWhereWithoutPatrolRouteInput[]
  deleteMany?: Prisma.PatrolPointScalarWhereInput | Prisma.PatrolPointScalarWhereInput[]
}

export type PatrolPointCreateNestedOneWithoutPatrolLogsInput = {
  create?: Prisma.XOR<Prisma.PatrolPointCreateWithoutPatrolLogsInput, Prisma.PatrolPointUncheckedCreateWithoutPatrolLogsInput>
  connectOrCreate?: Prisma.PatrolPointCreateOrConnectWithoutPatrolLogsInput
  connect?: Prisma.PatrolPointWhereUniqueInput
}

export type PatrolPointUpdateOneRequiredWithoutPatrolLogsNestedInput = {
  create?: Prisma.XOR<Prisma.PatrolPointCreateWithoutPatrolLogsInput, Prisma.PatrolPointUncheckedCreateWithoutPatrolLogsInput>
  connectOrCreate?: Prisma.PatrolPointCreateOrConnectWithoutPatrolLogsInput
  upsert?: Prisma.PatrolPointUpsertWithoutPatrolLogsInput
  connect?: Prisma.PatrolPointWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PatrolPointUpdateToOneWithWhereWithoutPatrolLogsInput, Prisma.PatrolPointUpdateWithoutPatrolLogsInput>, Prisma.PatrolPointUncheckedUpdateWithoutPatrolLogsInput>
}

export type PatrolPointCreateWithoutPatrolRouteInput = {
  id?: string
  label: string
  qrCodeValue: string
  patrolLogs?: Prisma.PatrolLogCreateNestedManyWithoutPatrolPointInput
}

export type PatrolPointUncheckedCreateWithoutPatrolRouteInput = {
  id?: string
  label: string
  qrCodeValue: string
  patrolLogs?: Prisma.PatrolLogUncheckedCreateNestedManyWithoutPatrolPointInput
}

export type PatrolPointCreateOrConnectWithoutPatrolRouteInput = {
  where: Prisma.PatrolPointWhereUniqueInput
  create: Prisma.XOR<Prisma.PatrolPointCreateWithoutPatrolRouteInput, Prisma.PatrolPointUncheckedCreateWithoutPatrolRouteInput>
}

export type PatrolPointCreateManyPatrolRouteInputEnvelope = {
  data: Prisma.PatrolPointCreateManyPatrolRouteInput | Prisma.PatrolPointCreateManyPatrolRouteInput[]
  skipDuplicates?: boolean
}

export type PatrolPointUpsertWithWhereUniqueWithoutPatrolRouteInput = {
  where: Prisma.PatrolPointWhereUniqueInput
  update: Prisma.XOR<Prisma.PatrolPointUpdateWithoutPatrolRouteInput, Prisma.PatrolPointUncheckedUpdateWithoutPatrolRouteInput>
  create: Prisma.XOR<Prisma.PatrolPointCreateWithoutPatrolRouteInput, Prisma.PatrolPointUncheckedCreateWithoutPatrolRouteInput>
}

export type PatrolPointUpdateWithWhereUniqueWithoutPatrolRouteInput = {
  where: Prisma.PatrolPointWhereUniqueInput
  data: Prisma.XOR<Prisma.PatrolPointUpdateWithoutPatrolRouteInput, Prisma.PatrolPointUncheckedUpdateWithoutPatrolRouteInput>
}

export type PatrolPointUpdateManyWithWhereWithoutPatrolRouteInput = {
  where: Prisma.PatrolPointScalarWhereInput
  data: Prisma.XOR<Prisma.PatrolPointUpdateManyMutationInput, Prisma.PatrolPointUncheckedUpdateManyWithoutPatrolRouteInput>
}

export type PatrolPointScalarWhereInput = {
  AND?: Prisma.PatrolPointScalarWhereInput | Prisma.PatrolPointScalarWhereInput[]
  OR?: Prisma.PatrolPointScalarWhereInput[]
  NOT?: Prisma.PatrolPointScalarWhereInput | Prisma.PatrolPointScalarWhereInput[]
  id?: Prisma.StringFilter<"PatrolPoint"> | string
  patrolRouteId?: Prisma.StringFilter<"PatrolPoint"> | string
  label?: Prisma.StringFilter<"PatrolPoint"> | string
  qrCodeValue?: Prisma.StringFilter<"PatrolPoint"> | string
}

export type PatrolPointCreateWithoutPatrolLogsInput = {
  id?: string
  label: string
  qrCodeValue: string
  patrolRoute: Prisma.PatrolRouteCreateNestedOneWithoutPatrolPointsInput
}

export type PatrolPointUncheckedCreateWithoutPatrolLogsInput = {
  id?: string
  patrolRouteId: string
  label: string
  qrCodeValue: string
}

export type PatrolPointCreateOrConnectWithoutPatrolLogsInput = {
  where: Prisma.PatrolPointWhereUniqueInput
  create: Prisma.XOR<Prisma.PatrolPointCreateWithoutPatrolLogsInput, Prisma.PatrolPointUncheckedCreateWithoutPatrolLogsInput>
}

export type PatrolPointUpsertWithoutPatrolLogsInput = {
  update: Prisma.XOR<Prisma.PatrolPointUpdateWithoutPatrolLogsInput, Prisma.PatrolPointUncheckedUpdateWithoutPatrolLogsInput>
  create: Prisma.XOR<Prisma.PatrolPointCreateWithoutPatrolLogsInput, Prisma.PatrolPointUncheckedCreateWithoutPatrolLogsInput>
  where?: Prisma.PatrolPointWhereInput
}

export type PatrolPointUpdateToOneWithWhereWithoutPatrolLogsInput = {
  where?: Prisma.PatrolPointWhereInput
  data: Prisma.XOR<Prisma.PatrolPointUpdateWithoutPatrolLogsInput, Prisma.PatrolPointUncheckedUpdateWithoutPatrolLogsInput>
}

export type PatrolPointUpdateWithoutPatrolLogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  qrCodeValue?: Prisma.StringFieldUpdateOperationsInput | string
  patrolRoute?: Prisma.PatrolRouteUpdateOneRequiredWithoutPatrolPointsNestedInput
}

export type PatrolPointUncheckedUpdateWithoutPatrolLogsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  patrolRouteId?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  qrCodeValue?: Prisma.StringFieldUpdateOperationsInput | string
}

export type PatrolPointCreateManyPatrolRouteInput = {
  id?: string
  label: string
  qrCodeValue: string
}

export type PatrolPointUpdateWithoutPatrolRouteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  qrCodeValue?: Prisma.StringFieldUpdateOperationsInput | string
  patrolLogs?: Prisma.PatrolLogUpdateManyWithoutPatrolPointNestedInput
}

export type PatrolPointUncheckedUpdateWithoutPatrolRouteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  qrCodeValue?: Prisma.StringFieldUpdateOperationsInput | string
  patrolLogs?: Prisma.PatrolLogUncheckedUpdateManyWithoutPatrolPointNestedInput
}

export type PatrolPointUncheckedUpdateManyWithoutPatrolRouteInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  label?: Prisma.StringFieldUpdateOperationsInput | string
  qrCodeValue?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type PatrolPointCountOutputType
 */

export type PatrolPointCountOutputType = {
  patrolLogs: number
}

export type PatrolPointCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  patrolLogs?: boolean | PatrolPointCountOutputTypeCountPatrolLogsArgs
}

/**
 * PatrolPointCountOutputType without action
 */
export type PatrolPointCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolPointCountOutputType
   */
  select?: Prisma.PatrolPointCountOutputTypeSelect<ExtArgs> | null
}

/**
 * PatrolPointCountOutputType without action
 */
export type PatrolPointCountOutputTypeCountPatrolLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PatrolLogWhereInput
}


export type PatrolPointSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  patrolRouteId?: boolean
  label?: boolean
  qrCodeValue?: boolean
  patrolRoute?: boolean | Prisma.PatrolRouteDefaultArgs<ExtArgs>
  patrolLogs?: boolean | Prisma.PatrolPoint$patrolLogsArgs<ExtArgs>
  _count?: boolean | Prisma.PatrolPointCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["patrolPoint"]>

export type PatrolPointSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  patrolRouteId?: boolean
  label?: boolean
  qrCodeValue?: boolean
  patrolRoute?: boolean | Prisma.PatrolRouteDefaultArgs<ExtArgs>
}, ExtArgs["result"]["patrolPoint"]>

export type PatrolPointSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  patrolRouteId?: boolean
  label?: boolean
  qrCodeValue?: boolean
  patrolRoute?: boolean | Prisma.PatrolRouteDefaultArgs<ExtArgs>
}, ExtArgs["result"]["patrolPoint"]>

export type PatrolPointSelectScalar = {
  id?: boolean
  patrolRouteId?: boolean
  label?: boolean
  qrCodeValue?: boolean
}

export type PatrolPointOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "patrolRouteId" | "label" | "qrCodeValue", ExtArgs["result"]["patrolPoint"]>
export type PatrolPointInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  patrolRoute?: boolean | Prisma.PatrolRouteDefaultArgs<ExtArgs>
  patrolLogs?: boolean | Prisma.PatrolPoint$patrolLogsArgs<ExtArgs>
  _count?: boolean | Prisma.PatrolPointCountOutputTypeDefaultArgs<ExtArgs>
}
export type PatrolPointIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  patrolRoute?: boolean | Prisma.PatrolRouteDefaultArgs<ExtArgs>
}
export type PatrolPointIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  patrolRoute?: boolean | Prisma.PatrolRouteDefaultArgs<ExtArgs>
}

export type $PatrolPointPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PatrolPoint"
  objects: {
    patrolRoute: Prisma.$PatrolRoutePayload<ExtArgs>
    patrolLogs: Prisma.$PatrolLogPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    patrolRouteId: string
    label: string
    qrCodeValue: string
  }, ExtArgs["result"]["patrolPoint"]>
  composites: {}
}

export type PatrolPointGetPayload<S extends boolean | null | undefined | PatrolPointDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PatrolPointPayload, S>

export type PatrolPointCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PatrolPointFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PatrolPointCountAggregateInputType | true
  }

export interface PatrolPointDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PatrolPoint'], meta: { name: 'PatrolPoint' } }
  /**
   * Find zero or one PatrolPoint that matches the filter.
   * @param {PatrolPointFindUniqueArgs} args - Arguments to find a PatrolPoint
   * @example
   * // Get one PatrolPoint
   * const patrolPoint = await prisma.patrolPoint.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PatrolPointFindUniqueArgs>(args: Prisma.SelectSubset<T, PatrolPointFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PatrolPointClient<runtime.Types.Result.GetResult<Prisma.$PatrolPointPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PatrolPoint that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PatrolPointFindUniqueOrThrowArgs} args - Arguments to find a PatrolPoint
   * @example
   * // Get one PatrolPoint
   * const patrolPoint = await prisma.patrolPoint.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PatrolPointFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PatrolPointFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PatrolPointClient<runtime.Types.Result.GetResult<Prisma.$PatrolPointPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PatrolPoint that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PatrolPointFindFirstArgs} args - Arguments to find a PatrolPoint
   * @example
   * // Get one PatrolPoint
   * const patrolPoint = await prisma.patrolPoint.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PatrolPointFindFirstArgs>(args?: Prisma.SelectSubset<T, PatrolPointFindFirstArgs<ExtArgs>>): Prisma.Prisma__PatrolPointClient<runtime.Types.Result.GetResult<Prisma.$PatrolPointPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PatrolPoint that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PatrolPointFindFirstOrThrowArgs} args - Arguments to find a PatrolPoint
   * @example
   * // Get one PatrolPoint
   * const patrolPoint = await prisma.patrolPoint.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PatrolPointFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PatrolPointFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PatrolPointClient<runtime.Types.Result.GetResult<Prisma.$PatrolPointPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PatrolPoints that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PatrolPointFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PatrolPoints
   * const patrolPoints = await prisma.patrolPoint.findMany()
   * 
   * // Get first 10 PatrolPoints
   * const patrolPoints = await prisma.patrolPoint.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const patrolPointWithIdOnly = await prisma.patrolPoint.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PatrolPointFindManyArgs>(args?: Prisma.SelectSubset<T, PatrolPointFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PatrolPointPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PatrolPoint.
   * @param {PatrolPointCreateArgs} args - Arguments to create a PatrolPoint.
   * @example
   * // Create one PatrolPoint
   * const PatrolPoint = await prisma.patrolPoint.create({
   *   data: {
   *     // ... data to create a PatrolPoint
   *   }
   * })
   * 
   */
  create<T extends PatrolPointCreateArgs>(args: Prisma.SelectSubset<T, PatrolPointCreateArgs<ExtArgs>>): Prisma.Prisma__PatrolPointClient<runtime.Types.Result.GetResult<Prisma.$PatrolPointPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PatrolPoints.
   * @param {PatrolPointCreateManyArgs} args - Arguments to create many PatrolPoints.
   * @example
   * // Create many PatrolPoints
   * const patrolPoint = await prisma.patrolPoint.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PatrolPointCreateManyArgs>(args?: Prisma.SelectSubset<T, PatrolPointCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PatrolPoints and returns the data saved in the database.
   * @param {PatrolPointCreateManyAndReturnArgs} args - Arguments to create many PatrolPoints.
   * @example
   * // Create many PatrolPoints
   * const patrolPoint = await prisma.patrolPoint.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PatrolPoints and only return the `id`
   * const patrolPointWithIdOnly = await prisma.patrolPoint.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PatrolPointCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PatrolPointCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PatrolPointPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PatrolPoint.
   * @param {PatrolPointDeleteArgs} args - Arguments to delete one PatrolPoint.
   * @example
   * // Delete one PatrolPoint
   * const PatrolPoint = await prisma.patrolPoint.delete({
   *   where: {
   *     // ... filter to delete one PatrolPoint
   *   }
   * })
   * 
   */
  delete<T extends PatrolPointDeleteArgs>(args: Prisma.SelectSubset<T, PatrolPointDeleteArgs<ExtArgs>>): Prisma.Prisma__PatrolPointClient<runtime.Types.Result.GetResult<Prisma.$PatrolPointPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PatrolPoint.
   * @param {PatrolPointUpdateArgs} args - Arguments to update one PatrolPoint.
   * @example
   * // Update one PatrolPoint
   * const patrolPoint = await prisma.patrolPoint.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PatrolPointUpdateArgs>(args: Prisma.SelectSubset<T, PatrolPointUpdateArgs<ExtArgs>>): Prisma.Prisma__PatrolPointClient<runtime.Types.Result.GetResult<Prisma.$PatrolPointPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PatrolPoints.
   * @param {PatrolPointDeleteManyArgs} args - Arguments to filter PatrolPoints to delete.
   * @example
   * // Delete a few PatrolPoints
   * const { count } = await prisma.patrolPoint.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PatrolPointDeleteManyArgs>(args?: Prisma.SelectSubset<T, PatrolPointDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PatrolPoints.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PatrolPointUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PatrolPoints
   * const patrolPoint = await prisma.patrolPoint.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PatrolPointUpdateManyArgs>(args: Prisma.SelectSubset<T, PatrolPointUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PatrolPoints and returns the data updated in the database.
   * @param {PatrolPointUpdateManyAndReturnArgs} args - Arguments to update many PatrolPoints.
   * @example
   * // Update many PatrolPoints
   * const patrolPoint = await prisma.patrolPoint.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PatrolPoints and only return the `id`
   * const patrolPointWithIdOnly = await prisma.patrolPoint.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PatrolPointUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PatrolPointUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PatrolPointPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PatrolPoint.
   * @param {PatrolPointUpsertArgs} args - Arguments to update or create a PatrolPoint.
   * @example
   * // Update or create a PatrolPoint
   * const patrolPoint = await prisma.patrolPoint.upsert({
   *   create: {
   *     // ... data to create a PatrolPoint
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PatrolPoint we want to update
   *   }
   * })
   */
  upsert<T extends PatrolPointUpsertArgs>(args: Prisma.SelectSubset<T, PatrolPointUpsertArgs<ExtArgs>>): Prisma.Prisma__PatrolPointClient<runtime.Types.Result.GetResult<Prisma.$PatrolPointPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PatrolPoints.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PatrolPointCountArgs} args - Arguments to filter PatrolPoints to count.
   * @example
   * // Count the number of PatrolPoints
   * const count = await prisma.patrolPoint.count({
   *   where: {
   *     // ... the filter for the PatrolPoints we want to count
   *   }
   * })
  **/
  count<T extends PatrolPointCountArgs>(
    args?: Prisma.Subset<T, PatrolPointCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PatrolPointCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PatrolPoint.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PatrolPointAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PatrolPointAggregateArgs>(args: Prisma.Subset<T, PatrolPointAggregateArgs>): Prisma.PrismaPromise<GetPatrolPointAggregateType<T>>

  /**
   * Group by PatrolPoint.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PatrolPointGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PatrolPointGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PatrolPointGroupByArgs['orderBy'] }
      : { orderBy?: PatrolPointGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PatrolPointGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPatrolPointGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PatrolPoint model
 */
readonly fields: PatrolPointFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PatrolPoint.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PatrolPointClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  patrolRoute<T extends Prisma.PatrolRouteDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PatrolRouteDefaultArgs<ExtArgs>>): Prisma.Prisma__PatrolRouteClient<runtime.Types.Result.GetResult<Prisma.$PatrolRoutePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  patrolLogs<T extends Prisma.PatrolPoint$patrolLogsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PatrolPoint$patrolLogsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PatrolLogPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PatrolPoint model
 */
export interface PatrolPointFieldRefs {
  readonly id: Prisma.FieldRef<"PatrolPoint", 'String'>
  readonly patrolRouteId: Prisma.FieldRef<"PatrolPoint", 'String'>
  readonly label: Prisma.FieldRef<"PatrolPoint", 'String'>
  readonly qrCodeValue: Prisma.FieldRef<"PatrolPoint", 'String'>
}
    

// Custom InputTypes
/**
 * PatrolPoint findUnique
 */
export type PatrolPointFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolPoint
   */
  select?: Prisma.PatrolPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolPoint
   */
  omit?: Prisma.PatrolPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolPointInclude<ExtArgs> | null
  /**
   * Filter, which PatrolPoint to fetch.
   */
  where: Prisma.PatrolPointWhereUniqueInput
}

/**
 * PatrolPoint findUniqueOrThrow
 */
export type PatrolPointFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolPoint
   */
  select?: Prisma.PatrolPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolPoint
   */
  omit?: Prisma.PatrolPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolPointInclude<ExtArgs> | null
  /**
   * Filter, which PatrolPoint to fetch.
   */
  where: Prisma.PatrolPointWhereUniqueInput
}

/**
 * PatrolPoint findFirst
 */
export type PatrolPointFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolPoint
   */
  select?: Prisma.PatrolPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolPoint
   */
  omit?: Prisma.PatrolPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolPointInclude<ExtArgs> | null
  /**
   * Filter, which PatrolPoint to fetch.
   */
  where?: Prisma.PatrolPointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PatrolPoints to fetch.
   */
  orderBy?: Prisma.PatrolPointOrderByWithRelationInput | Prisma.PatrolPointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PatrolPoints.
   */
  cursor?: Prisma.PatrolPointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PatrolPoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PatrolPoints.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PatrolPoints.
   */
  distinct?: Prisma.PatrolPointScalarFieldEnum | Prisma.PatrolPointScalarFieldEnum[]
}

/**
 * PatrolPoint findFirstOrThrow
 */
export type PatrolPointFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolPoint
   */
  select?: Prisma.PatrolPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolPoint
   */
  omit?: Prisma.PatrolPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolPointInclude<ExtArgs> | null
  /**
   * Filter, which PatrolPoint to fetch.
   */
  where?: Prisma.PatrolPointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PatrolPoints to fetch.
   */
  orderBy?: Prisma.PatrolPointOrderByWithRelationInput | Prisma.PatrolPointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PatrolPoints.
   */
  cursor?: Prisma.PatrolPointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PatrolPoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PatrolPoints.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PatrolPoints.
   */
  distinct?: Prisma.PatrolPointScalarFieldEnum | Prisma.PatrolPointScalarFieldEnum[]
}

/**
 * PatrolPoint findMany
 */
export type PatrolPointFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolPoint
   */
  select?: Prisma.PatrolPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolPoint
   */
  omit?: Prisma.PatrolPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolPointInclude<ExtArgs> | null
  /**
   * Filter, which PatrolPoints to fetch.
   */
  where?: Prisma.PatrolPointWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PatrolPoints to fetch.
   */
  orderBy?: Prisma.PatrolPointOrderByWithRelationInput | Prisma.PatrolPointOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PatrolPoints.
   */
  cursor?: Prisma.PatrolPointWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PatrolPoints from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PatrolPoints.
   */
  skip?: number
  distinct?: Prisma.PatrolPointScalarFieldEnum | Prisma.PatrolPointScalarFieldEnum[]
}

/**
 * PatrolPoint create
 */
export type PatrolPointCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolPoint
   */
  select?: Prisma.PatrolPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolPoint
   */
  omit?: Prisma.PatrolPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolPointInclude<ExtArgs> | null
  /**
   * The data needed to create a PatrolPoint.
   */
  data: Prisma.XOR<Prisma.PatrolPointCreateInput, Prisma.PatrolPointUncheckedCreateInput>
}

/**
 * PatrolPoint createMany
 */
export type PatrolPointCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PatrolPoints.
   */
  data: Prisma.PatrolPointCreateManyInput | Prisma.PatrolPointCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PatrolPoint createManyAndReturn
 */
export type PatrolPointCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolPoint
   */
  select?: Prisma.PatrolPointSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolPoint
   */
  omit?: Prisma.PatrolPointOmit<ExtArgs> | null
  /**
   * The data used to create many PatrolPoints.
   */
  data: Prisma.PatrolPointCreateManyInput | Prisma.PatrolPointCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolPointIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PatrolPoint update
 */
export type PatrolPointUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolPoint
   */
  select?: Prisma.PatrolPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolPoint
   */
  omit?: Prisma.PatrolPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolPointInclude<ExtArgs> | null
  /**
   * The data needed to update a PatrolPoint.
   */
  data: Prisma.XOR<Prisma.PatrolPointUpdateInput, Prisma.PatrolPointUncheckedUpdateInput>
  /**
   * Choose, which PatrolPoint to update.
   */
  where: Prisma.PatrolPointWhereUniqueInput
}

/**
 * PatrolPoint updateMany
 */
export type PatrolPointUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PatrolPoints.
   */
  data: Prisma.XOR<Prisma.PatrolPointUpdateManyMutationInput, Prisma.PatrolPointUncheckedUpdateManyInput>
  /**
   * Filter which PatrolPoints to update
   */
  where?: Prisma.PatrolPointWhereInput
  /**
   * Limit how many PatrolPoints to update.
   */
  limit?: number
}

/**
 * PatrolPoint updateManyAndReturn
 */
export type PatrolPointUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolPoint
   */
  select?: Prisma.PatrolPointSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolPoint
   */
  omit?: Prisma.PatrolPointOmit<ExtArgs> | null
  /**
   * The data used to update PatrolPoints.
   */
  data: Prisma.XOR<Prisma.PatrolPointUpdateManyMutationInput, Prisma.PatrolPointUncheckedUpdateManyInput>
  /**
   * Filter which PatrolPoints to update
   */
  where?: Prisma.PatrolPointWhereInput
  /**
   * Limit how many PatrolPoints to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolPointIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PatrolPoint upsert
 */
export type PatrolPointUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolPoint
   */
  select?: Prisma.PatrolPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolPoint
   */
  omit?: Prisma.PatrolPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolPointInclude<ExtArgs> | null
  /**
   * The filter to search for the PatrolPoint to update in case it exists.
   */
  where: Prisma.PatrolPointWhereUniqueInput
  /**
   * In case the PatrolPoint found by the `where` argument doesn't exist, create a new PatrolPoint with this data.
   */
  create: Prisma.XOR<Prisma.PatrolPointCreateInput, Prisma.PatrolPointUncheckedCreateInput>
  /**
   * In case the PatrolPoint was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PatrolPointUpdateInput, Prisma.PatrolPointUncheckedUpdateInput>
}

/**
 * PatrolPoint delete
 */
export type PatrolPointDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolPoint
   */
  select?: Prisma.PatrolPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolPoint
   */
  omit?: Prisma.PatrolPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolPointInclude<ExtArgs> | null
  /**
   * Filter which PatrolPoint to delete.
   */
  where: Prisma.PatrolPointWhereUniqueInput
}

/**
 * PatrolPoint deleteMany
 */
export type PatrolPointDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PatrolPoints to delete
   */
  where?: Prisma.PatrolPointWhereInput
  /**
   * Limit how many PatrolPoints to delete.
   */
  limit?: number
}

/**
 * PatrolPoint.patrolLogs
 */
export type PatrolPoint$patrolLogsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolLog
   */
  select?: Prisma.PatrolLogSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolLog
   */
  omit?: Prisma.PatrolLogOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolLogInclude<ExtArgs> | null
  where?: Prisma.PatrolLogWhereInput
  orderBy?: Prisma.PatrolLogOrderByWithRelationInput | Prisma.PatrolLogOrderByWithRelationInput[]
  cursor?: Prisma.PatrolLogWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PatrolLogScalarFieldEnum | Prisma.PatrolLogScalarFieldEnum[]
}

/**
 * PatrolPoint without action
 */
export type PatrolPointDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PatrolPoint
   */
  select?: Prisma.PatrolPointSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PatrolPoint
   */
  omit?: Prisma.PatrolPointOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PatrolPointInclude<ExtArgs> | null
}
