
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PersonnelFile` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model PersonnelFile
 * 
 */
export type PersonnelFileModel = runtime.Types.Result.DefaultSelection<Prisma.$PersonnelFilePayload>

export type AggregatePersonnelFile = {
  _count: PersonnelFileCountAggregateOutputType | null
  _min: PersonnelFileMinAggregateOutputType | null
  _max: PersonnelFileMaxAggregateOutputType | null
}

export type PersonnelFileMinAggregateOutputType = {
  id: string | null
  userId: string | null
  address: string | null
  emergencyPhone: string | null
  hireDate: Date | null
  terminationDate: Date | null
  notes: string | null
}

export type PersonnelFileMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  address: string | null
  emergencyPhone: string | null
  hireDate: Date | null
  terminationDate: Date | null
  notes: string | null
}

export type PersonnelFileCountAggregateOutputType = {
  id: number
  userId: number
  address: number
  emergencyPhone: number
  hireDate: number
  terminationDate: number
  notes: number
  _all: number
}


export type PersonnelFileMinAggregateInputType = {
  id?: true
  userId?: true
  address?: true
  emergencyPhone?: true
  hireDate?: true
  terminationDate?: true
  notes?: true
}

export type PersonnelFileMaxAggregateInputType = {
  id?: true
  userId?: true
  address?: true
  emergencyPhone?: true
  hireDate?: true
  terminationDate?: true
  notes?: true
}

export type PersonnelFileCountAggregateInputType = {
  id?: true
  userId?: true
  address?: true
  emergencyPhone?: true
  hireDate?: true
  terminationDate?: true
  notes?: true
  _all?: true
}

export type PersonnelFileAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PersonnelFile to aggregate.
   */
  where?: Prisma.PersonnelFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PersonnelFiles to fetch.
   */
  orderBy?: Prisma.PersonnelFileOrderByWithRelationInput | Prisma.PersonnelFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PersonnelFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PersonnelFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PersonnelFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PersonnelFiles
  **/
  _count?: true | PersonnelFileCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PersonnelFileMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PersonnelFileMaxAggregateInputType
}

export type GetPersonnelFileAggregateType<T extends PersonnelFileAggregateArgs> = {
      [P in keyof T & keyof AggregatePersonnelFile]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePersonnelFile[P]>
    : Prisma.GetScalarType<T[P], AggregatePersonnelFile[P]>
}




export type PersonnelFileGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PersonnelFileWhereInput
  orderBy?: Prisma.PersonnelFileOrderByWithAggregationInput | Prisma.PersonnelFileOrderByWithAggregationInput[]
  by: Prisma.PersonnelFileScalarFieldEnum[] | Prisma.PersonnelFileScalarFieldEnum
  having?: Prisma.PersonnelFileScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PersonnelFileCountAggregateInputType | true
  _min?: PersonnelFileMinAggregateInputType
  _max?: PersonnelFileMaxAggregateInputType
}

export type PersonnelFileGroupByOutputType = {
  id: string
  userId: string
  address: string | null
  emergencyPhone: string | null
  hireDate: Date | null
  terminationDate: Date | null
  notes: string | null
  _count: PersonnelFileCountAggregateOutputType | null
  _min: PersonnelFileMinAggregateOutputType | null
  _max: PersonnelFileMaxAggregateOutputType | null
}

type GetPersonnelFileGroupByPayload<T extends PersonnelFileGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PersonnelFileGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PersonnelFileGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PersonnelFileGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PersonnelFileGroupByOutputType[P]>
      }
    >
  >



export type PersonnelFileWhereInput = {
  AND?: Prisma.PersonnelFileWhereInput | Prisma.PersonnelFileWhereInput[]
  OR?: Prisma.PersonnelFileWhereInput[]
  NOT?: Prisma.PersonnelFileWhereInput | Prisma.PersonnelFileWhereInput[]
  id?: Prisma.StringFilter<"PersonnelFile"> | string
  userId?: Prisma.StringFilter<"PersonnelFile"> | string
  address?: Prisma.StringNullableFilter<"PersonnelFile"> | string | null
  emergencyPhone?: Prisma.StringNullableFilter<"PersonnelFile"> | string | null
  hireDate?: Prisma.DateTimeNullableFilter<"PersonnelFile"> | Date | string | null
  terminationDate?: Prisma.DateTimeNullableFilter<"PersonnelFile"> | Date | string | null
  notes?: Prisma.StringNullableFilter<"PersonnelFile"> | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type PersonnelFileOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  emergencyPhone?: Prisma.SortOrderInput | Prisma.SortOrder
  hireDate?: Prisma.SortOrderInput | Prisma.SortOrder
  terminationDate?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type PersonnelFileWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId?: string
  AND?: Prisma.PersonnelFileWhereInput | Prisma.PersonnelFileWhereInput[]
  OR?: Prisma.PersonnelFileWhereInput[]
  NOT?: Prisma.PersonnelFileWhereInput | Prisma.PersonnelFileWhereInput[]
  address?: Prisma.StringNullableFilter<"PersonnelFile"> | string | null
  emergencyPhone?: Prisma.StringNullableFilter<"PersonnelFile"> | string | null
  hireDate?: Prisma.DateTimeNullableFilter<"PersonnelFile"> | Date | string | null
  terminationDate?: Prisma.DateTimeNullableFilter<"PersonnelFile"> | Date | string | null
  notes?: Prisma.StringNullableFilter<"PersonnelFile"> | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "userId">

export type PersonnelFileOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  address?: Prisma.SortOrderInput | Prisma.SortOrder
  emergencyPhone?: Prisma.SortOrderInput | Prisma.SortOrder
  hireDate?: Prisma.SortOrderInput | Prisma.SortOrder
  terminationDate?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.PersonnelFileCountOrderByAggregateInput
  _max?: Prisma.PersonnelFileMaxOrderByAggregateInput
  _min?: Prisma.PersonnelFileMinOrderByAggregateInput
}

export type PersonnelFileScalarWhereWithAggregatesInput = {
  AND?: Prisma.PersonnelFileScalarWhereWithAggregatesInput | Prisma.PersonnelFileScalarWhereWithAggregatesInput[]
  OR?: Prisma.PersonnelFileScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PersonnelFileScalarWhereWithAggregatesInput | Prisma.PersonnelFileScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PersonnelFile"> | string
  userId?: Prisma.StringWithAggregatesFilter<"PersonnelFile"> | string
  address?: Prisma.StringNullableWithAggregatesFilter<"PersonnelFile"> | string | null
  emergencyPhone?: Prisma.StringNullableWithAggregatesFilter<"PersonnelFile"> | string | null
  hireDate?: Prisma.DateTimeNullableWithAggregatesFilter<"PersonnelFile"> | Date | string | null
  terminationDate?: Prisma.DateTimeNullableWithAggregatesFilter<"PersonnelFile"> | Date | string | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"PersonnelFile"> | string | null
}

export type PersonnelFileCreateInput = {
  id?: string
  address?: string | null
  emergencyPhone?: string | null
  hireDate?: Date | string | null
  terminationDate?: Date | string | null
  notes?: string | null
  user: Prisma.UserCreateNestedOneWithoutPersonnelFileInput
}

export type PersonnelFileUncheckedCreateInput = {
  id?: string
  userId: string
  address?: string | null
  emergencyPhone?: string | null
  hireDate?: Date | string | null
  terminationDate?: Date | string | null
  notes?: string | null
}

export type PersonnelFileUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emergencyPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hireDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  terminationDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutPersonnelFileNestedInput
}

export type PersonnelFileUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emergencyPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hireDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  terminationDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PersonnelFileCreateManyInput = {
  id?: string
  userId: string
  address?: string | null
  emergencyPhone?: string | null
  hireDate?: Date | string | null
  terminationDate?: Date | string | null
  notes?: string | null
}

export type PersonnelFileUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emergencyPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hireDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  terminationDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PersonnelFileUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emergencyPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hireDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  terminationDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PersonnelFileNullableScalarRelationFilter = {
  is?: Prisma.PersonnelFileWhereInput | null
  isNot?: Prisma.PersonnelFileWhereInput | null
}

export type PersonnelFileCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  address?: Prisma.SortOrder
  emergencyPhone?: Prisma.SortOrder
  hireDate?: Prisma.SortOrder
  terminationDate?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type PersonnelFileMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  address?: Prisma.SortOrder
  emergencyPhone?: Prisma.SortOrder
  hireDate?: Prisma.SortOrder
  terminationDate?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type PersonnelFileMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  address?: Prisma.SortOrder
  emergencyPhone?: Prisma.SortOrder
  hireDate?: Prisma.SortOrder
  terminationDate?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type PersonnelFileCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PersonnelFileCreateWithoutUserInput, Prisma.PersonnelFileUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PersonnelFileCreateOrConnectWithoutUserInput
  connect?: Prisma.PersonnelFileWhereUniqueInput
}

export type PersonnelFileUncheckedCreateNestedOneWithoutUserInput = {
  create?: Prisma.XOR<Prisma.PersonnelFileCreateWithoutUserInput, Prisma.PersonnelFileUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PersonnelFileCreateOrConnectWithoutUserInput
  connect?: Prisma.PersonnelFileWhereUniqueInput
}

export type PersonnelFileUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PersonnelFileCreateWithoutUserInput, Prisma.PersonnelFileUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PersonnelFileCreateOrConnectWithoutUserInput
  upsert?: Prisma.PersonnelFileUpsertWithoutUserInput
  disconnect?: Prisma.PersonnelFileWhereInput | boolean
  delete?: Prisma.PersonnelFileWhereInput | boolean
  connect?: Prisma.PersonnelFileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PersonnelFileUpdateToOneWithWhereWithoutUserInput, Prisma.PersonnelFileUpdateWithoutUserInput>, Prisma.PersonnelFileUncheckedUpdateWithoutUserInput>
}

export type PersonnelFileUncheckedUpdateOneWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.PersonnelFileCreateWithoutUserInput, Prisma.PersonnelFileUncheckedCreateWithoutUserInput>
  connectOrCreate?: Prisma.PersonnelFileCreateOrConnectWithoutUserInput
  upsert?: Prisma.PersonnelFileUpsertWithoutUserInput
  disconnect?: Prisma.PersonnelFileWhereInput | boolean
  delete?: Prisma.PersonnelFileWhereInput | boolean
  connect?: Prisma.PersonnelFileWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.PersonnelFileUpdateToOneWithWhereWithoutUserInput, Prisma.PersonnelFileUpdateWithoutUserInput>, Prisma.PersonnelFileUncheckedUpdateWithoutUserInput>
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type PersonnelFileCreateWithoutUserInput = {
  id?: string
  address?: string | null
  emergencyPhone?: string | null
  hireDate?: Date | string | null
  terminationDate?: Date | string | null
  notes?: string | null
}

export type PersonnelFileUncheckedCreateWithoutUserInput = {
  id?: string
  address?: string | null
  emergencyPhone?: string | null
  hireDate?: Date | string | null
  terminationDate?: Date | string | null
  notes?: string | null
}

export type PersonnelFileCreateOrConnectWithoutUserInput = {
  where: Prisma.PersonnelFileWhereUniqueInput
  create: Prisma.XOR<Prisma.PersonnelFileCreateWithoutUserInput, Prisma.PersonnelFileUncheckedCreateWithoutUserInput>
}

export type PersonnelFileUpsertWithoutUserInput = {
  update: Prisma.XOR<Prisma.PersonnelFileUpdateWithoutUserInput, Prisma.PersonnelFileUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.PersonnelFileCreateWithoutUserInput, Prisma.PersonnelFileUncheckedCreateWithoutUserInput>
  where?: Prisma.PersonnelFileWhereInput
}

export type PersonnelFileUpdateToOneWithWhereWithoutUserInput = {
  where?: Prisma.PersonnelFileWhereInput
  data: Prisma.XOR<Prisma.PersonnelFileUpdateWithoutUserInput, Prisma.PersonnelFileUncheckedUpdateWithoutUserInput>
}

export type PersonnelFileUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emergencyPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hireDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  terminationDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PersonnelFileUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  address?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  emergencyPhone?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hireDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  terminationDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type PersonnelFileSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  address?: boolean
  emergencyPhone?: boolean
  hireDate?: boolean
  terminationDate?: boolean
  notes?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["personnelFile"]>

export type PersonnelFileSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  address?: boolean
  emergencyPhone?: boolean
  hireDate?: boolean
  terminationDate?: boolean
  notes?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["personnelFile"]>

export type PersonnelFileSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  address?: boolean
  emergencyPhone?: boolean
  hireDate?: boolean
  terminationDate?: boolean
  notes?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["personnelFile"]>

export type PersonnelFileSelectScalar = {
  id?: boolean
  userId?: boolean
  address?: boolean
  emergencyPhone?: boolean
  hireDate?: boolean
  terminationDate?: boolean
  notes?: boolean
}

export type PersonnelFileOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "address" | "emergencyPhone" | "hireDate" | "terminationDate" | "notes", ExtArgs["result"]["personnelFile"]>
export type PersonnelFileInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PersonnelFileIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type PersonnelFileIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $PersonnelFilePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PersonnelFile"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    address: string | null
    emergencyPhone: string | null
    hireDate: Date | null
    terminationDate: Date | null
    notes: string | null
  }, ExtArgs["result"]["personnelFile"]>
  composites: {}
}

export type PersonnelFileGetPayload<S extends boolean | null | undefined | PersonnelFileDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PersonnelFilePayload, S>

export type PersonnelFileCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PersonnelFileFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PersonnelFileCountAggregateInputType | true
  }

export interface PersonnelFileDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PersonnelFile'], meta: { name: 'PersonnelFile' } }
  /**
   * Find zero or one PersonnelFile that matches the filter.
   * @param {PersonnelFileFindUniqueArgs} args - Arguments to find a PersonnelFile
   * @example
   * // Get one PersonnelFile
   * const personnelFile = await prisma.personnelFile.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PersonnelFileFindUniqueArgs>(args: Prisma.SelectSubset<T, PersonnelFileFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PersonnelFileClient<runtime.Types.Result.GetResult<Prisma.$PersonnelFilePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PersonnelFile that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PersonnelFileFindUniqueOrThrowArgs} args - Arguments to find a PersonnelFile
   * @example
   * // Get one PersonnelFile
   * const personnelFile = await prisma.personnelFile.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PersonnelFileFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PersonnelFileFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PersonnelFileClient<runtime.Types.Result.GetResult<Prisma.$PersonnelFilePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PersonnelFile that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonnelFileFindFirstArgs} args - Arguments to find a PersonnelFile
   * @example
   * // Get one PersonnelFile
   * const personnelFile = await prisma.personnelFile.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PersonnelFileFindFirstArgs>(args?: Prisma.SelectSubset<T, PersonnelFileFindFirstArgs<ExtArgs>>): Prisma.Prisma__PersonnelFileClient<runtime.Types.Result.GetResult<Prisma.$PersonnelFilePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PersonnelFile that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonnelFileFindFirstOrThrowArgs} args - Arguments to find a PersonnelFile
   * @example
   * // Get one PersonnelFile
   * const personnelFile = await prisma.personnelFile.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PersonnelFileFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PersonnelFileFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PersonnelFileClient<runtime.Types.Result.GetResult<Prisma.$PersonnelFilePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PersonnelFiles that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonnelFileFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PersonnelFiles
   * const personnelFiles = await prisma.personnelFile.findMany()
   * 
   * // Get first 10 PersonnelFiles
   * const personnelFiles = await prisma.personnelFile.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const personnelFileWithIdOnly = await prisma.personnelFile.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PersonnelFileFindManyArgs>(args?: Prisma.SelectSubset<T, PersonnelFileFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PersonnelFilePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PersonnelFile.
   * @param {PersonnelFileCreateArgs} args - Arguments to create a PersonnelFile.
   * @example
   * // Create one PersonnelFile
   * const PersonnelFile = await prisma.personnelFile.create({
   *   data: {
   *     // ... data to create a PersonnelFile
   *   }
   * })
   * 
   */
  create<T extends PersonnelFileCreateArgs>(args: Prisma.SelectSubset<T, PersonnelFileCreateArgs<ExtArgs>>): Prisma.Prisma__PersonnelFileClient<runtime.Types.Result.GetResult<Prisma.$PersonnelFilePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PersonnelFiles.
   * @param {PersonnelFileCreateManyArgs} args - Arguments to create many PersonnelFiles.
   * @example
   * // Create many PersonnelFiles
   * const personnelFile = await prisma.personnelFile.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PersonnelFileCreateManyArgs>(args?: Prisma.SelectSubset<T, PersonnelFileCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PersonnelFiles and returns the data saved in the database.
   * @param {PersonnelFileCreateManyAndReturnArgs} args - Arguments to create many PersonnelFiles.
   * @example
   * // Create many PersonnelFiles
   * const personnelFile = await prisma.personnelFile.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PersonnelFiles and only return the `id`
   * const personnelFileWithIdOnly = await prisma.personnelFile.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PersonnelFileCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PersonnelFileCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PersonnelFilePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PersonnelFile.
   * @param {PersonnelFileDeleteArgs} args - Arguments to delete one PersonnelFile.
   * @example
   * // Delete one PersonnelFile
   * const PersonnelFile = await prisma.personnelFile.delete({
   *   where: {
   *     // ... filter to delete one PersonnelFile
   *   }
   * })
   * 
   */
  delete<T extends PersonnelFileDeleteArgs>(args: Prisma.SelectSubset<T, PersonnelFileDeleteArgs<ExtArgs>>): Prisma.Prisma__PersonnelFileClient<runtime.Types.Result.GetResult<Prisma.$PersonnelFilePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PersonnelFile.
   * @param {PersonnelFileUpdateArgs} args - Arguments to update one PersonnelFile.
   * @example
   * // Update one PersonnelFile
   * const personnelFile = await prisma.personnelFile.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PersonnelFileUpdateArgs>(args: Prisma.SelectSubset<T, PersonnelFileUpdateArgs<ExtArgs>>): Prisma.Prisma__PersonnelFileClient<runtime.Types.Result.GetResult<Prisma.$PersonnelFilePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PersonnelFiles.
   * @param {PersonnelFileDeleteManyArgs} args - Arguments to filter PersonnelFiles to delete.
   * @example
   * // Delete a few PersonnelFiles
   * const { count } = await prisma.personnelFile.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PersonnelFileDeleteManyArgs>(args?: Prisma.SelectSubset<T, PersonnelFileDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PersonnelFiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonnelFileUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PersonnelFiles
   * const personnelFile = await prisma.personnelFile.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PersonnelFileUpdateManyArgs>(args: Prisma.SelectSubset<T, PersonnelFileUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PersonnelFiles and returns the data updated in the database.
   * @param {PersonnelFileUpdateManyAndReturnArgs} args - Arguments to update many PersonnelFiles.
   * @example
   * // Update many PersonnelFiles
   * const personnelFile = await prisma.personnelFile.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PersonnelFiles and only return the `id`
   * const personnelFileWithIdOnly = await prisma.personnelFile.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PersonnelFileUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PersonnelFileUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PersonnelFilePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PersonnelFile.
   * @param {PersonnelFileUpsertArgs} args - Arguments to update or create a PersonnelFile.
   * @example
   * // Update or create a PersonnelFile
   * const personnelFile = await prisma.personnelFile.upsert({
   *   create: {
   *     // ... data to create a PersonnelFile
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PersonnelFile we want to update
   *   }
   * })
   */
  upsert<T extends PersonnelFileUpsertArgs>(args: Prisma.SelectSubset<T, PersonnelFileUpsertArgs<ExtArgs>>): Prisma.Prisma__PersonnelFileClient<runtime.Types.Result.GetResult<Prisma.$PersonnelFilePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PersonnelFiles.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonnelFileCountArgs} args - Arguments to filter PersonnelFiles to count.
   * @example
   * // Count the number of PersonnelFiles
   * const count = await prisma.personnelFile.count({
   *   where: {
   *     // ... the filter for the PersonnelFiles we want to count
   *   }
   * })
  **/
  count<T extends PersonnelFileCountArgs>(
    args?: Prisma.Subset<T, PersonnelFileCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PersonnelFileCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PersonnelFile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonnelFileAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PersonnelFileAggregateArgs>(args: Prisma.Subset<T, PersonnelFileAggregateArgs>): Prisma.PrismaPromise<GetPersonnelFileAggregateType<T>>

  /**
   * Group by PersonnelFile.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PersonnelFileGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PersonnelFileGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PersonnelFileGroupByArgs['orderBy'] }
      : { orderBy?: PersonnelFileGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PersonnelFileGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPersonnelFileGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PersonnelFile model
 */
readonly fields: PersonnelFileFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PersonnelFile.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PersonnelFileClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PersonnelFile model
 */
export interface PersonnelFileFieldRefs {
  readonly id: Prisma.FieldRef<"PersonnelFile", 'String'>
  readonly userId: Prisma.FieldRef<"PersonnelFile", 'String'>
  readonly address: Prisma.FieldRef<"PersonnelFile", 'String'>
  readonly emergencyPhone: Prisma.FieldRef<"PersonnelFile", 'String'>
  readonly hireDate: Prisma.FieldRef<"PersonnelFile", 'DateTime'>
  readonly terminationDate: Prisma.FieldRef<"PersonnelFile", 'DateTime'>
  readonly notes: Prisma.FieldRef<"PersonnelFile", 'String'>
}
    

// Custom InputTypes
/**
 * PersonnelFile findUnique
 */
export type PersonnelFileFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonnelFile
   */
  select?: Prisma.PersonnelFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonnelFile
   */
  omit?: Prisma.PersonnelFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonnelFileInclude<ExtArgs> | null
  /**
   * Filter, which PersonnelFile to fetch.
   */
  where: Prisma.PersonnelFileWhereUniqueInput
}

/**
 * PersonnelFile findUniqueOrThrow
 */
export type PersonnelFileFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonnelFile
   */
  select?: Prisma.PersonnelFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonnelFile
   */
  omit?: Prisma.PersonnelFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonnelFileInclude<ExtArgs> | null
  /**
   * Filter, which PersonnelFile to fetch.
   */
  where: Prisma.PersonnelFileWhereUniqueInput
}

/**
 * PersonnelFile findFirst
 */
export type PersonnelFileFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonnelFile
   */
  select?: Prisma.PersonnelFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonnelFile
   */
  omit?: Prisma.PersonnelFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonnelFileInclude<ExtArgs> | null
  /**
   * Filter, which PersonnelFile to fetch.
   */
  where?: Prisma.PersonnelFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PersonnelFiles to fetch.
   */
  orderBy?: Prisma.PersonnelFileOrderByWithRelationInput | Prisma.PersonnelFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PersonnelFiles.
   */
  cursor?: Prisma.PersonnelFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PersonnelFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PersonnelFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PersonnelFiles.
   */
  distinct?: Prisma.PersonnelFileScalarFieldEnum | Prisma.PersonnelFileScalarFieldEnum[]
}

/**
 * PersonnelFile findFirstOrThrow
 */
export type PersonnelFileFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonnelFile
   */
  select?: Prisma.PersonnelFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonnelFile
   */
  omit?: Prisma.PersonnelFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonnelFileInclude<ExtArgs> | null
  /**
   * Filter, which PersonnelFile to fetch.
   */
  where?: Prisma.PersonnelFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PersonnelFiles to fetch.
   */
  orderBy?: Prisma.PersonnelFileOrderByWithRelationInput | Prisma.PersonnelFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PersonnelFiles.
   */
  cursor?: Prisma.PersonnelFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PersonnelFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PersonnelFiles.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PersonnelFiles.
   */
  distinct?: Prisma.PersonnelFileScalarFieldEnum | Prisma.PersonnelFileScalarFieldEnum[]
}

/**
 * PersonnelFile findMany
 */
export type PersonnelFileFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonnelFile
   */
  select?: Prisma.PersonnelFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonnelFile
   */
  omit?: Prisma.PersonnelFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonnelFileInclude<ExtArgs> | null
  /**
   * Filter, which PersonnelFiles to fetch.
   */
  where?: Prisma.PersonnelFileWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PersonnelFiles to fetch.
   */
  orderBy?: Prisma.PersonnelFileOrderByWithRelationInput | Prisma.PersonnelFileOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PersonnelFiles.
   */
  cursor?: Prisma.PersonnelFileWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PersonnelFiles from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PersonnelFiles.
   */
  skip?: number
  distinct?: Prisma.PersonnelFileScalarFieldEnum | Prisma.PersonnelFileScalarFieldEnum[]
}

/**
 * PersonnelFile create
 */
export type PersonnelFileCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonnelFile
   */
  select?: Prisma.PersonnelFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonnelFile
   */
  omit?: Prisma.PersonnelFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonnelFileInclude<ExtArgs> | null
  /**
   * The data needed to create a PersonnelFile.
   */
  data: Prisma.XOR<Prisma.PersonnelFileCreateInput, Prisma.PersonnelFileUncheckedCreateInput>
}

/**
 * PersonnelFile createMany
 */
export type PersonnelFileCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PersonnelFiles.
   */
  data: Prisma.PersonnelFileCreateManyInput | Prisma.PersonnelFileCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PersonnelFile createManyAndReturn
 */
export type PersonnelFileCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonnelFile
   */
  select?: Prisma.PersonnelFileSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PersonnelFile
   */
  omit?: Prisma.PersonnelFileOmit<ExtArgs> | null
  /**
   * The data used to create many PersonnelFiles.
   */
  data: Prisma.PersonnelFileCreateManyInput | Prisma.PersonnelFileCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonnelFileIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PersonnelFile update
 */
export type PersonnelFileUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonnelFile
   */
  select?: Prisma.PersonnelFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonnelFile
   */
  omit?: Prisma.PersonnelFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonnelFileInclude<ExtArgs> | null
  /**
   * The data needed to update a PersonnelFile.
   */
  data: Prisma.XOR<Prisma.PersonnelFileUpdateInput, Prisma.PersonnelFileUncheckedUpdateInput>
  /**
   * Choose, which PersonnelFile to update.
   */
  where: Prisma.PersonnelFileWhereUniqueInput
}

/**
 * PersonnelFile updateMany
 */
export type PersonnelFileUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PersonnelFiles.
   */
  data: Prisma.XOR<Prisma.PersonnelFileUpdateManyMutationInput, Prisma.PersonnelFileUncheckedUpdateManyInput>
  /**
   * Filter which PersonnelFiles to update
   */
  where?: Prisma.PersonnelFileWhereInput
  /**
   * Limit how many PersonnelFiles to update.
   */
  limit?: number
}

/**
 * PersonnelFile updateManyAndReturn
 */
export type PersonnelFileUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonnelFile
   */
  select?: Prisma.PersonnelFileSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PersonnelFile
   */
  omit?: Prisma.PersonnelFileOmit<ExtArgs> | null
  /**
   * The data used to update PersonnelFiles.
   */
  data: Prisma.XOR<Prisma.PersonnelFileUpdateManyMutationInput, Prisma.PersonnelFileUncheckedUpdateManyInput>
  /**
   * Filter which PersonnelFiles to update
   */
  where?: Prisma.PersonnelFileWhereInput
  /**
   * Limit how many PersonnelFiles to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonnelFileIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PersonnelFile upsert
 */
export type PersonnelFileUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonnelFile
   */
  select?: Prisma.PersonnelFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonnelFile
   */
  omit?: Prisma.PersonnelFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonnelFileInclude<ExtArgs> | null
  /**
   * The filter to search for the PersonnelFile to update in case it exists.
   */
  where: Prisma.PersonnelFileWhereUniqueInput
  /**
   * In case the PersonnelFile found by the `where` argument doesn't exist, create a new PersonnelFile with this data.
   */
  create: Prisma.XOR<Prisma.PersonnelFileCreateInput, Prisma.PersonnelFileUncheckedCreateInput>
  /**
   * In case the PersonnelFile was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PersonnelFileUpdateInput, Prisma.PersonnelFileUncheckedUpdateInput>
}

/**
 * PersonnelFile delete
 */
export type PersonnelFileDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonnelFile
   */
  select?: Prisma.PersonnelFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonnelFile
   */
  omit?: Prisma.PersonnelFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonnelFileInclude<ExtArgs> | null
  /**
   * Filter which PersonnelFile to delete.
   */
  where: Prisma.PersonnelFileWhereUniqueInput
}

/**
 * PersonnelFile deleteMany
 */
export type PersonnelFileDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PersonnelFiles to delete
   */
  where?: Prisma.PersonnelFileWhereInput
  /**
   * Limit how many PersonnelFiles to delete.
   */
  limit?: number
}

/**
 * PersonnelFile without action
 */
export type PersonnelFileDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PersonnelFile
   */
  select?: Prisma.PersonnelFileSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PersonnelFile
   */
  omit?: Prisma.PersonnelFileOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PersonnelFileInclude<ExtArgs> | null
}
